/**
 * Shared tracker state and cached DOM references.
 *
 * This file centralizes mutable top-level state and element lookups for the
 * script-based app architecture. Feature modules may read these values, but
 * should keep domain-specific behavior in their own files.
 */
let character = null;
let characterLibrary = null;
let characterDraftMode = false;
const CHARACTER_SETUP_STEPS = [
  { id: "concept", label: "Concept" },
  { id: "traits", label: "Attributes" },
  { id: "skills", label: "Skills" },
  { id: "edges", label: "Edges" },
  { id: "hindrances", label: "Hindrances" },
  { id: "powers", label: "Powers" },
  { id: "gear", label: "Gear" },
  { id: "review", label: "Review" },
];
var characterSetupStep = "concept";
var characterSetupReviewOpen = false;
var setupResumeOnBoot = false;
let saveTimer = null;
let edgeEditingId = "";
let hindranceEditingId = "";
let powerEditingId = "";
let advanceEditingId = "";
let advancePowerTargetIds = [];
let advanceManualEdgeMode = false;

const $ = (selector) => document.querySelector(selector);

const els = {
  characterName: $("#characterName"),
  characterSubtitle: $("#characterSubtitle"),
  saveState: $("#saveState"),
  undoBtn: $("#undoBtn"),
  redoBtn: $("#redoBtn"),
  woundsValue: $("#woundsValue"),
  woundPenalty: $("#woundPenalty"),
  woundsNote: $("#woundsNote"),
  fatigueValue: $("#fatigueValue"),
  fatiguePenalty: $("#fatiguePenalty"),
  fatigueNote: $("#fatigueNote"),
  benniesValue: $("#benniesValue"),
  bennyStart: $("#bennyStart"),
  convictionValue: $("#convictionValue"),
  paceValue: $("#paceValue"),
  parryValue: $("#parryValue"),
  toughnessValue: $("#toughnessValue"),
  armorSelect: $("#armorSelect"),
  armorNote: $("#armorNote"),
  armorStrengthPill: $("#armorStrengthPill"),
  weaponStrengthPill: $("#weaponStrengthPill"),
  moneyDisplay: $("#moneyDisplay"),
  moneyInput: $("#moneyInput"),
  addMoneyBtn: $("#addMoneyBtn"),
  spendMoneyBtn: $("#spendMoneyBtn"),
  resourcesList: $("#resourcesList"),
  addManualPowerPointsBtn: $("#addManualPowerPointsBtn"),
  combatStatusResources: $("#combatStatusResources"),
  combatArmorLocations: $("#combatArmorLocations"),
  combatPenaltyTotal: $("#combatPenaltyTotal"),
  combatPenaltySummary: $("#combatPenaltySummary"),
  combatPenaltyBreakdown: $("#combatPenaltyBreakdown"),
  combatEncumbranceSummary: $("#combatEncumbranceSummary"),
  actionCardPanel: $("#actionCardPanel"),
  actionCardStatusPill: $("#actionCardStatusPill"),
  actionCardSummary: $("#actionCardSummary"),
  actionCardRules: $("#actionCardRules"),
  actionCardInput: $("#actionCardInput"),
  actionCardSecondaryField: $("#actionCardSecondaryField"),
  actionCardSecondaryInput: $("#actionCardSecondaryInput"),
  actionCardNotesInput: $("#actionCardNotesInput"),
  clearActionCardsBtn: $("#clearActionCardsBtn"),
  playPowerPointsCard: $("#playPowerPointsCard"),
  playPowerPointsList: $("#playPowerPointsList"),
  combatDeclarationCard: $("#combatDeclarationCard"),
  combatDeclarationStatusPill: $("#combatDeclarationStatusPill"),
  combatDeclarationActionHints: $("#combatDeclarationActionHints"),
  combatDeclarationReminders: $("#combatDeclarationReminders"),
  combatDeclarationActionInput: $("#combatDeclarationActionInput"),
  combatDeclarationCountInput: $("#combatDeclarationCountInput"),
  combatDeclarationWeaponInput: $("#combatDeclarationWeaponInput"),
  combatDeclarationTargetInput: $("#combatDeclarationTargetInput"),
  combatDeclarationDetailsInput: $("#combatDeclarationDetailsInput"),
  combatDeclarationPreview: $("#combatDeclarationPreview"),
  combatDeclarationResultInput: $("#combatDeclarationResultInput"),
  combatDeclarationWoundsInput: $("#combatDeclarationWoundsInput"),
  combatDeclarationFatigueInput: $("#combatDeclarationFatigueInput"),
  combatDeclarationBenniesInput: $("#combatDeclarationBenniesInput"),
  combatDeclarationConditionInput: $("#combatDeclarationConditionInput"),
  combatDeclarationConditionModeInput: $(
    "#combatDeclarationConditionModeInput",
  ),
  combatDeclarationAmmoInput: $("#combatDeclarationAmmoInput"),
  applyCombatDeclarationResultBtn: $("#applyCombatDeclarationResultBtn"),
  clearCombatDeclarationBtn: $("#clearCombatDeclarationBtn"),
  clearCombatDeclarationLogBtn: $("#clearCombatDeclarationLogBtn"),
  combatDeclarationResultLog: $("#combatDeclarationResultLog"),
  playResourcesCard: $("#playResourcesCard"),
  playResourcesList: $("#playResourcesList"),
  playActivePowersCard: $("#playActivePowersCard"),
  playActivePowersList: $("#playActivePowersList"),
  combatHucksterCard: $("#combatHucksterCard"),
  combatHucksterHelper: $("#combatHucksterHelper"),
  combatConsumablesCard: $("#combatConsumablesCard"),
  combatConsumablesList: $("#combatConsumablesList"),
  combatRemindersCard: $("#combatRemindersCard"),
  combatRemindersList: $("#combatRemindersList"),
  keyConditionsList: $("#keyConditionsList"),
  playWeaponList: $("#playWeaponList"),
  playAmmoReserves: $("#playAmmoReserves"),
  characterSummaryName: $("#characterSummaryName"),
  characterDossierSubtitle: $("#characterDossierSubtitle"),
  characterSourceBadge: $("#characterSourceBadge"),
  characterStatusStrip: $("#characterStatusStrip"),
  characterBasicsList: $("#characterBasicsList"),
  characterSetupPanel: $("#characterSetupPanel"),
  characterSetupStepper: $("#characterSetupStepper"),
  characterSetupContent: $("#characterSetupContent"),
  characterDossierLayout: $("#characterDossierLayout"),
  reviewSetupBtn: $("#reviewSetupBtn"),
  attributesList: $("#attributesList"),
  skillsList: $("#skillsList"),
  advanceSummaryList: $("#advanceSummaryList"),
  advanceWarningList: $("#advanceWarningList"),
  advancesList: $("#advancesList"),
  showAdvanceFormBtn: $("#showAdvanceFormBtn"),
  advanceEditorPanel: $("#advanceEditorPanel"),
  advanceEditorTitle: $("#advanceEditorTitle"),
  advanceNumberInput: $("#advanceNumberInput"),
  advanceRankInput: $("#advanceRankInput"),
  advanceTypeInput: $("#advanceTypeInput"),
  advanceDynamicFields: $("#advanceDynamicFields"),
  advanceSummaryInput: $("#advanceSummaryInput"),
  advanceSummaryField: $("#advanceSummaryField"),
  advanceTargetNameInput: $("#advanceTargetNameInput"),
  advanceTargetNameField: $("#advanceTargetNameField"),
  advanceTargetTypeInput: $("#advanceTargetTypeInput"),
  advanceTargetTypeField: $("#advanceTargetTypeField"),
  advanceNotesInput: $("#advanceNotesInput"),
  advanceSourceInput: $("#advanceSourceInput"),
  advancePowerPointAmountInput: $("#advancePowerPointAmountInput"),
  advancePowerPointAmountField: $("#advancePowerPointAmountField"),
  showAdvanceNotesBtn: $("#showAdvanceNotesBtn"),
  advanceNotesField: $("#advanceNotesField"),
  advanceApplyPanel: $("#advanceApplyPanel"),
  advanceApplyInput: $("#advanceApplyInput"),
  advanceAppliedNote: $("#advanceAppliedNote"),
  advanceWarningText: $("#advanceWarningText"),
  saveAdvanceBtn: $("#saveAdvanceBtn"),
  cancelAdvanceEditBtn: $("#cancelAdvanceEditBtn"),
  edgesList: $("#edgesList"),
  hindrancesList: $("#hindrancesList"),
  characterDerivedDetails: $("#characterDerivedDetails"),
  characterArcaneSummary: $("#characterArcaneSummary"),
  characterEquippedSummary: $("#characterEquippedSummary"),
  characterBackgroundSummary: $("#characterBackgroundSummary"),
  showEdgeFormBtn: $("#showEdgeFormBtn"),
  edgeEditorPanel: $("#edgeEditorPanel"),
  edgeEditorTitle: $("#edgeEditorTitle"),
  edgeCatalogSelect: $("#edgeCatalogSelect"),
  edgeNameInput: $("#edgeNameInput"),
  edgeCategoryInput: $("#edgeCategoryInput"),
  edgeRankInput: $("#edgeRankInput"),
  edgeSourceInput: $("#edgeSourceInput"),
  edgeRequirementsInput: $("#edgeRequirementsInput"),
  edgeSubchoiceInput: $("#edgeSubchoiceInput"),
  edgeSubchoiceOptions: $("#edgeSubchoiceOptions"),
  edgeSubchoiceHelp: $("#edgeSubchoiceHelp"),
  edgeSummaryInput: $("#edgeSummaryInput"),
  edgeNotesInput: $("#edgeNotesInput"),
  edgeWarningText: $("#edgeWarningText"),
  saveEdgeBtn: $("#saveEdgeBtn"),
  cancelEdgeEditBtn: $("#cancelEdgeEditBtn"),
  showHindranceFormBtn: $("#showHindranceFormBtn"),
  hindranceEditorPanel: $("#hindranceEditorPanel"),
  hindranceEditorTitle: $("#hindranceEditorTitle"),
  hindranceCatalogSelect: $("#hindranceCatalogSelect"),
  hindranceNameInput: $("#hindranceNameInput"),
  hindranceSeverityInput: $("#hindranceSeverityInput"),
  hindranceSourceInput: $("#hindranceSourceInput"),
  hindranceSummaryInput: $("#hindranceSummaryInput"),
  hindranceNotesInput: $("#hindranceNotesInput"),
  hindranceWarningText: $("#hindranceWarningText"),
  saveHindranceBtn: $("#saveHindranceBtn"),
  cancelHindranceEditBtn: $("#cancelHindranceEditBtn"),
  organizationBookkeepingPanel: $("#organizationBookkeepingPanel"),
  organizationSuggestionList: $("#organizationSuggestionList"),
  organizationBookkeepingList: $("#organizationBookkeepingList"),
  addOrganizationRecordBtn: $("#addOrganizationRecordBtn"),
  arcaneDetailSummary: $("#arcaneDetailSummary"),
  arcaneRemindersList: $("#arcaneRemindersList"),
  importWarningsList: $("#importWarningsList"),
  longFormNotesList: $("#longFormNotesList"),
  arcaneSummary: $("#arcaneSummary"),
  powersList: $("#powersList"),
  powerSetupNotice: $("#powerSetupNotice"),
  powerCatalogSearch: $("#powerCatalogSearch"),
  powerRankFilter: $("#powerRankFilter"),
  powerValidOnlyInput: $("#powerValidOnlyInput"),
  powerMarshalOverrideInput: $("#powerMarshalOverrideInput"),
  powerCatalogSelect: $("#powerCatalogSelect"),
  powerCatalogWarning: $("#powerCatalogWarning"),
  powerCatalogPreview: $("#powerCatalogPreview"),
  addCatalogPowerBtn: $("#addCatalogPowerBtn"),
  addRequiredPowerBtn: $("#addRequiredPowerBtn"),
  hucksterAvailablePowers: $("#hucksterAvailablePowers"),
  powerNameInput: $("#powerNameInput"),
  powerCostInput: $("#powerCostInput"),
  powerRangeInput: $("#powerRangeInput"),
  powerDurationInput: $("#powerDurationInput"),
  powerSourceInput: $("#powerSourceInput"),
  powerTrappingInput: $("#powerTrappingInput"),
  powerSummaryInput: $("#powerSummaryInput"),
  powerNotesInput: $("#powerNotesInput"),
  addPowerBtn: $("#addPowerBtn"),
  activePowersList: $("#activePowersList"),
  madScienceDevicesPanel: $("#madScienceDevicesPanel"),
  madScienceDevicePowerSelect: $("#madScienceDevicePowerSelect"),
  addMadScienceDeviceBtn: $("#addMadScienceDeviceBtn"),
  madScienceDevicesList: $("#madScienceDevicesList"),
  hucksterDealPanel: $("#hucksterDealPanel"),
  hucksterSelectedPower: $("#hucksterSelectedPower"),
  hucksterRequiredPowerPoints: $("#hucksterRequiredPowerPoints"),
  hucksterGamblingRollResult: $("#hucksterGamblingRollResult"),
  hucksterCardsDrawn: $("#hucksterCardsDrawn"),
  hucksterPokerHand: $("#hucksterPokerHand"),
  hucksterTemporaryPowerPoints: $("#hucksterTemporaryPowerPoints"),
  hucksterShortagePenalty: $("#hucksterShortagePenalty"),
  hucksterLeftoverPowerPoints: $("#hucksterLeftoverPowerPoints"),
  hucksterAnteBennySpent: $("#hucksterAnteBennySpent"),
  hucksterUsedJoker: $("#hucksterUsedJoker"),
  hucksterBackfireTriggered: $("#hucksterBackfireTriggered"),
  hucksterNotes: $("#hucksterNotes"),
  weaponList: $("#weaponList"),
  weaponCatalogSelect: $("#weaponCatalogSelect"),
  weaponNameInput: $("#weaponNameInput"),
  weaponQtyInput: $("#weaponQtyInput"),
  weaponDamageInput: $("#weaponDamageInput"),
  weaponRangeInput: $("#weaponRangeInput"),
  weaponApInput: $("#weaponApInput"),
  weaponRofInput: $("#weaponRofInput"),
  weaponCapacityInput: $("#weaponCapacityInput"),
  weaponAmmoTypeSelect: $("#weaponAmmoTypeSelect"),
  weaponAddForm: $("#weaponAddForm"),
  addWeaponBtn: $("#addWeaponBtn"),
  cancelWeaponAddBtn: $("#cancelWeaponAddBtn"),
  weaponCatalogPreview: $("#weaponCatalogPreview"),
  weaponTemplate: $("#weaponTemplate"),
  ammoReserves: $("#ammoReserves"),
  ammoGearSelect: $("#ammoGearSelect"),
  ammoLabelInput: $("#ammoLabelInput"),
  ammoCountInput: $("#ammoCountInput"),
  ammoCaliberSelect: $("#ammoCaliberSelect"),
  ammoNoteInput: $("#ammoNoteInput"),
  ammoAddForm: $("#ammoAddForm"),
  addAmmoBtn: $("#addAmmoBtn"),
  cancelAmmoAddBtn: $("#cancelAmmoAddBtn"),
  ammoGearPreview: $("#ammoGearPreview"),
  armorLocationList: $("#armorLocationList"),
  armorInventoryList: $("#armorInventoryList"),
  armorCatalogSelect: $("#armorCatalogSelect"),
  armorNameInput: $("#armorNameInput"),
  armorCountInput: $("#armorCountInput"),
  armorValueInput: $("#armorValueInput"),
  armorLocationSelect: $("#armorLocationSelect"),
  armorAddForm: $("#armorAddForm"),
  addArmorBtn: $("#addArmorBtn"),
  cancelArmorAddBtn: $("#cancelArmorAddBtn"),
  armorCatalogPreview: $("#armorCatalogPreview"),
  conditionsList: $("#conditionsList"),
  clearTempConditionsBtn: $("#clearTempConditionsBtn"),
  consumablesList: $("#consumablesList"),
  encumbranceSummaryPill: $("#encumbranceSummaryPill"),
  encumbranceDetails: $("#encumbranceDetails"),
  encumbranceWarning: $("#encumbranceWarning"),
  remindersList: $("#remindersList"),
  gearSelect: $("#gearSelect"),
  inventoryNameInput: $("#inventoryNameInput"),
  inventoryCountInput: $("#inventoryCountInput"),
  inventoryUnitsField: $("#inventoryUnitsField"),
  inventoryUnitsLabel: $("#inventoryUnitsLabel"),
  inventoryUnitsInput: $("#inventoryUnitsInput"),
  inventoryLocationSelect: $("#inventoryLocationSelect"),
  inventoryNoteInput: $("#inventoryNoteInput"),
  gearAddForm: $("#gearAddForm"),
  addInventoryBtn: $("#addInventoryBtn"),
  cancelInventoryAddBtn: $("#cancelInventoryAddBtn"),
  gearPreview: $("#gearPreview"),
  inventoryList: $("#inventoryList"),
  storageLocationInput: $("#storageLocationInput"),
  addStorageLocationBtn: $("#addStorageLocationBtn"),
  storageLocationList: $("#storageLocationList"),
  vehicleCatalogSelect: $("#vehicleCatalogSelect"),
  vehicleNameInput: $("#vehicleNameInput"),
  vehicleQtyInput: $("#vehicleQtyInput"),
  vehicleNoteInput: $("#vehicleNoteInput"),
  vehicleAddForm: $("#vehicleAddForm"),
  addVehicleBtn: $("#addVehicleBtn"),
  cancelVehicleAddBtn: $("#cancelVehicleAddBtn"),
  vehicleCatalogPreview: $("#vehicleCatalogPreview"),
  vehicleList: $("#vehicleList"),
  notesArea: $("#notesArea"),
  newSessionBtn: $("#newSessionBtn"),
  headerToolsMenu: $("#headerToolsMenu"),
  exportBtn: $("#exportBtn"),
  importFile: $("#importFile"),
  pasteImportBtn: $("#pasteImportBtn"),
  pasteImportPanel: $("#pasteImportPanel"),
  importJsonText: $("#importJsonText"),
  confirmPasteImportBtn: $("#confirmPasteImportBtn"),
  cancelPasteImportBtn: $("#cancelPasteImportBtn"),
  resetBtn: $("#resetBtn"),
  localDataStatusBadges: $("#localDataStatusBadges"),
  localDataAppDetails: $("#localDataAppDetails"),
  localDataStorageDetails: $("#localDataStorageDetails"),
  privacyLegalDemoLink: $("#privacyLegalDemoLink"),
  localDataExportTrackerBtn: $("#localDataExportTrackerBtn"),
  localDataExportFullBtn: $("#localDataExportFullBtn"),
  localDataOpenImportBtn: $("#localDataOpenImportBtn"),
  localDataShowWelcomeBtn: $("#localDataShowWelcomeBtn"),
  localDataClearDraftBtn: $("#localDataClearDraftBtn"),
  localDataClearDemoFlagBtn: $("#localDataClearDemoFlagBtn"),
  localDataClearAllBtn: $("#localDataClearAllBtn"),
  catalogSearchInput: $("#catalogSearchInput"),
  catalogFilterFields: $("#catalogFilterFields"),
  catalogResultsList: $("#catalogResultsList"),
  catalogResultSummary: $("#catalogResultSummary"),
  catalogDetailPanel: $("#catalogDetailPanel"),
  landingCharacterPicker: $("#landingCharacterPicker"),
  landingCharacterSelect: $("#landingCharacterSelect"),
  librarySummaryPill: $("#librarySummaryPill"),
  characterProfileEditor: $("#characterProfileEditor"),
  characterProfileStatus: $("#characterProfileStatus"),
  characterLibraryList: $("#characterLibraryList"),
  librarySaveCurrentBtn: $("#librarySaveCurrentBtn"),
  libraryDuplicateActiveBtn: $("#libraryDuplicateActiveBtn"),
  libraryReviewSetupBtn: $("#libraryReviewSetupBtn"),
};
