const DEADLANDS_HINDRANCE_CATALOG = [
  ["dl-hindrance-ailin", "Ailin’", "Minor or Major", "Penalty to rolls made to resist Fatigue. Minor is worse than normal by 1; Major by 2. A Critical Failure can worsen the condition or create a terminal story moment at Major severity."],
  ["dl-hindrance-cursed", "Cursed", "Major", "For each player character with this Hindrance, the Marshal starts with one additional Benny."],
  ["dl-hindrance-grim-servant-o-death", "Grim Servant o’ Death", "Major", "Wild Card only. Adds +1 to all damage rolls, but a Critical Failure on an attack hits the nearest ally with a raise."],
  ["dl-hindrance-heavy-sleeper", "Heavy Sleeper", "Minor", "Takes a large penalty to wake up and to stay awake."],
  ["dl-hindrance-lyin-eyes", "Lyin’ Eyes", "Minor", "Penalty to social rolls that require lying; also penalizes bluffing in poker or faro."],
  ["dl-hindrance-night-terrors", "Night Terrors", "Major", "Constant nightmares weaken resolve, causing a penalty to all Spirit rolls."],
  ["dl-hindrance-old-ways-oath", "Old Ways Oath", "Minor", "Character rejects modern technology. If faithful, gains a free reroll on Spirit rolls. Violating the oath suppresses the benefit temporarily, longer for ghost-rock use."],
  ["dl-hindrance-talisman", "Talisman", "Minor or Major", "Arcane character suffers an arcane skill penalty without their talisman. Minor and Major differ by penalty size. Mad scientists are not eligible."],
  ["dl-hindrance-tenderfoot", "Tenderfoot", "Major", "If wounded, suffers an extra action penalty. Cannot take Don’t Get ’im Riled!"],
  ["dl-hindrance-trouble-magnet", "Trouble Magnet", "Minor or Major", "Minor makes Critical Failure consequences worse. Major causes random negative targeting to hit this character."],
].map(([id, name, severity, shortSummary]) => ({
  id,
  name,
  type: "hindrance",
  severity,
  shortSummary,
  source: "Deadlands: The Weird West",
  isCustom: false,
}));

const DEADLANDS_EDGE_CATALOG = [
  ["dl-edge-arcane-background-blessed", "Arcane Background (Blessed)", "Background", "Novice", "Spirit d6+, Faith d4+", "Grants Blessed casting: Faith arcane skill, 15 Power Points, holy symbol plus two chosen starting powers, Blessed power list, divine sin/backlash rules.", "Required"],
  ["dl-edge-arcane-background-chi-master", "Arcane Background (Chi Master)", "Background", "Novice", "Agility d6+, Spirit d6+, Martial Artist, Focus d4+", "Grants Chi Master casting: Focus arcane skill, 15 Power Points, deflection plus two chosen starting powers, internal/self-focused casting limitations.", "Required"],
  ["dl-edge-arcane-background-huckster", "Arcane Background (Huckster)", "Background", "Novice", "Gambling d6+, Spellcasting d4+", "Grants Huckster casting: Spellcasting arcane skill, 10 Power Points, three starting powers, Deal with the Devil rules, huckster backlash.", ""],
  ["dl-edge-arcane-background-mad-scientist", "Arcane Background (Mad Scientist)", "Background", "Novice", "Smarts d8+, Science d6+, Weird Science d4+", "Grants Mad Scientist casting: Weird Science arcane skill, 15 Power Points, two starting powers, gizmo/invention framing, malfunction rules.", ""],
  ["dl-edge-arcane-background-shaman", "Arcane Background (Shaman)", "Background", "Novice", "Spirit d8+, Faith d4+", "Grants Shaman casting: Faith arcane skill, 15 Power Points, two starting powers, Shaman power list, nature-spirit backlash and Old Ways context.", ""],
  ["dl-edge-gallows-humor", "Gallows Humor", "Background", "Novice", "Taunt d6+", "Allows Taunt instead of Spirit for Fear checks. A raise can support allies facing the same Fear check.", ""],
  ["dl-edge-veteran-o-the-weird-west", "Veteran o’ the Weird West", "Background", "Novice", "Wild Card, Spirit d6+, Occult d6+", "Starts at Seasoned or one Rank higher than the posse, gaining four Advances, but draws for a serious Weird West complication.", ""],
  ["dl-edge-dont-get-im-riled", "Don’t Get ’im Riled!", "Combat", "Novice", "None beyond Rank", "Adds current Wound levels to melee damage rolls.", ""],
  ["dl-edge-duelist", "Duelist", "Combat", "Novice", "Shooting d6+", "Grants two extra Hole Cards at the start of a formal duel.", ""],
  ["dl-edge-fan-the-hammer", "Fan the Hammer", "Combat", "Seasoned", "Agility d8+, Shooting d8+", "With a fully loaded single-action revolver, fire up to six shots as one action. Each shot suffers a Shooting penalty.", ""],
  ["dl-edge-improved-fan-the-hammer", "Improved Fan the Hammer", "Combat", "Heroic", "Agility d10+, Fan the Hammer, Shooting d10+", "Same as Fan the Hammer, but with a smaller Shooting penalty.", ""],
  ["dl-edge-quick-draw", "Quick Draw", "Combat", "Novice", "Agility d8+", "When spending a Benny for an extra Action Card, draw two and choose from available options. Also improves Athletics rolls to interrupt or resist interruption.", "Required"],
  ["dl-edge-agent", "Agent", "Professional", "Novice", "Smarts d8+, Fighting d6+, Occult d6+, Research d6+, Shooting d6+", "Makes the character a U.S. Agent. Grants organization status, starting gear, pay, badge benefits, and access to Agent favors/rank advancement.", ""],
  ["dl-edge-born-in-the-saddle", "Born in the Saddle", "Professional", "Novice", "Agility d8+, Riding d6+", "Free reroll on Riding rolls. Also improves the character’s horse movement.", ""],
  ["dl-edge-card-sharp", "Card Sharp", "Professional", "Novice", "Gambling d6+", "Free reroll on Gambling rolls, including Huckster Deal with the Devil Gambling rolls.", ""],
  ["dl-edge-guts", "Guts", "Professional", "Novice", "Spirit d6+", "Free reroll on Fear checks.", ""],
  ["dl-edge-scout", "Scout", "Professional", "Seasoned", "Woodsman", "Improves wilderness travel awareness, tracking, and route knowledge. Can detect travel encounters before they hit the posse.", ""],
  ["dl-edge-soldier", "Soldier", "Professional", "Novice", "Strength d6+, Vigor d6+", "Military-service Edge. Gives rank/pay/Obligation context if still serving. Higher starting rank is possible but increases Obligation and has extra expectations.", ""],
  ["dl-edge-tale-teller", "Tale-Teller", "Professional", "Novice", "Performance or Persuasion d8+", "Helps lower local Fear Levels. On a strong success, the tale-teller and supporters can earn Conviction.", ""],
  ["dl-edge-territorial-ranger", "Territorial Ranger", "Professional", "Novice", "Vigor d6+, Fighting d6+, Intimidation d6+, Riding d6+, Shooting d6+, Survival d4+", "Makes the character a Territorial Ranger. Grants organization status, starting gear, badge benefits, pay/favor context, and access to Ranger advancement.", ""],
  ["dl-edge-reputation", "Reputation", "Social", "Veteran", "None beyond Rank", "Choose good or bad reputation. Good reputation gives a Persuasion reroll with people who know the character; bad reputation gives an Intimidation bonus with people who know the character.", "Required"],
  ["dl-edge-grit", "Grit", "Weird", "Veteran", "Spirit d8+, Guts", "Reduces Fear check penalties and stacks with Brave.", ""],
  ["dl-edge-harrowed", "Harrowed", "Weird", "Novice", "Wild Card, Spirit d6+", "Character begins play as undead Harrowed. Grants Harrowed rules package and access to Harrowed Edges. Character-creation-only unless the Marshal says otherwise.", ""],
  ["dl-edge-knack", "Knack", "Weird", "Novice", "None beyond Rank", "Character chooses one folklore-based birth omen that grants a specific supernatural trick. Needs a subchoice.", "Required"],
  ["dl-edge-behold-a-pale-horse", "Behold a Pale Horse…", "Legendary", "Legendary", "None beyond Rank", "Grants a special war horse that is Fearless, has Danger Sense, is a Wild Card, and starts each session with its own Bennies.", ""],
  ["dl-edge-damned", "Damned", "Legendary", "Legendary", "Wild Card, Spirit d6+, Reputation", "If killed, the character automatically returns as Harrowed. After returning, this Edge can become an additional Harrowed Edge.", ""],
  ["dl-edge-fast-as-lightning", "Fast as Lightning", "Legendary", "Legendary", "Agility d10+, Quick", "Character can take a fourth action. Maximum Multi-Action Penalty increases accordingly.", ""],
  ["dl-edge-right-hand-of-the-devil", "Right Hand of the Devil", "Legendary", "Legendary", "Trademark Weapon, Shooting/Fighting/Athletics d10+", "Chosen favored weapon becomes a relic and deals one extra damage die. The benefit is tied to the weapon.", "Required"],
  ["dl-edge-true-grit", "True Grit", "Legendary", "Legendary", "Spirit d10+, Grit", "Ignores Fear check penalties and may reroll on the Fear Effects Table after failing.", ""],
  ["dl-edge-grade-2", "Grade 2", "Organization", "Seasoned", "Agent", "Character is already an Agent Grade 2. Grants mnemomizer, possible Gatling upgrade, three Favors, and broader supernatural knowledge.", ""],
  ["dl-edge-man-of-a-thousand-faces", "Man of a Thousand Faces", "Organization", "Seasoned", "Agent, Performance d8+", "Improves Performance rolls to impersonate a general type; more specific impersonations still carry penalties. Disguise kit helps offset penalties.", ""],
  ["dl-edge-true-believer", "True Believer", "Arcane", "Novice", "Spirit d10+, Arcane Background (Blessed), Faith d6+", "Free reroll on Faith rolls.", ""],
  ["dl-edge-flock", "Flock", "Arcane", "Veteran", "Arcane Background (Blessed), Persuasion d8+", "Grants five follower Allies using Townsfolk-style stats. Lost followers are replaced over time. Can be taken repeatedly at Legendary.", "Required"],
  ["dl-edge-superior-kung-fu", "Superior Kung Fu", "Arcane", "Novice", "Spirit d6+, Arcane Background (Chi Master), Fighting d8+", "Choose one kung fu style each time the Edge is taken. The character can assume one known style as a free action at the start of their turn.", "Required"],
  ["dl-edge-celestial-kung-fu", "Celestial Kung Fu", "Arcane", "Veteran", "Spirit d8+, Superior Kung Fu, Fighting d10+", "Grants another Superior Kung Fu style and allows two styles to be active at once.", "Required"],
  ["dl-edge-cat-eyes", "Cat Eyes", "Arcane", "Novice", "Harrowed", "Ignores Dim and Dark lighting penalties.", ""],
  ["dl-edge-improved-cat-eyes", "Improved Cat Eyes", "Arcane", "Seasoned", "Cat Eyes, Harrowed", "Ignores all lighting penalties.", ""],
  ["dl-edge-chill-o-the-grave", "Chill o’ the Grave", "Arcane", "Seasoned", "Harrowed", "Spend a Benny and an action to make living creatures in a Large Blast Template centered on the Harrowed Vulnerable unless protected from cold.", ""],
  ["dl-edge-claws", "Claws", "Arcane", "Novice", "Harrowed", "Gains retractable claws dealing Str+d6. Extending or retracting is a free action.", ""],
  ["dl-edge-improved-claws", "Improved Claws", "Arcane", "Veteran", "Claws, Harrowed", "Claws improve to Str+d8 with AP 2.", ""],
  ["dl-edge-ghost", "Ghost", "Arcane", "Heroic", "Harrowed", "Can become incorporeal at the start of turn as a free action. While ghosted, visible but intangible, Distracted, and still affected by magic.", ""],
  ["dl-edge-hellfire", "Hellfire", "Arcane", "Heroic", "Harrowed", "Once per turn, use an action to attack with Athletics in a Cone Template for fire damage; targets may Evade.", ""],
  ["dl-edge-implacable", "Implacable", "Arcane", "Heroic", "Harrowed", "Can take one extra Wound before Incapacitation. Stacks with Tough as Nails style Edges.", "Required"],
  ["dl-edge-infest", "Infest", "Arcane", "Novice", "Harrowed", "Spend a Benny and an action to control an existing nearby insect swarm for about five minutes.", ""],
  ["dl-edge-soul-eater", "Soul Eater", "Arcane", "Veteran", "Harrowed", "After causing a Wound with a barehanded/claw Fighting attack, make a Spirit roll at a penalty to heal one Wound or one Fatigue.", ""],
  ["dl-edge-spook", "Spook", "Arcane", "Novice", "Harrowed", "As an action, force one visible/nearby target to make a penalized Fear check. Can take Fatigue to affect all targets within 12 inches.", ""],
  ["dl-edge-stitchin", "Stitchin’", "Arcane", "Novice", "Harrowed", "Natural healing rolls happen daily instead of every five days if the Harrowed consumes meat for each attempt.", ""],
  ["dl-edge-improved-stitchin", "Improved Stitchin’", "Arcane", "Veteran", "Harrowed, Stitchin’", "Natural healing rolls happen hourly instead of daily.", ""],
  ["dl-edge-supernatural-attribute", "Supernatural Attribute", "Arcane", "Novice", "Harrowed", "Raises one chosen attribute by two die types and increases that Trait’s limit, including linked skills. Can be taken once per attribute.", "Required"],
  ["dl-edge-wither", "Wither", "Arcane", "Novice", "Harrowed", "Touch attack with opposed Spirit. On success, lowers target Strength for one hour; raise also lowers Vigor. Does not stack on same target.", ""],
  ["dl-edge-hexslinging", "Hexslinging", "Arcane", "Seasoned", "Arcane Background (Huckster), Shooting d8+", "Grants ammo whammy and lets the huckster make rune-carved hex guns. Certain powers can be cast on/with the hex gun without Multi-Action penalty.", ""],
  ["dl-edge-high-roller", "High Roller", "Arcane", "Seasoned", "Spirit d8+, Arcane Background (Huckster), Spellcasting d6+", "Draw one extra card when Dealing with the Devil.", ""],
  ["dl-edge-improved-high-roller", "Improved High Roller", "Arcane", "Veteran", "High Roller", "Draw two extra cards total when Dealing with the Devil.", ""],
  ["dl-edge-old-hand", "Old Hand", "Arcane", "Heroic", "Arcane Background (Huckster), Spellcasting d10+", "After forming a five-card poker hand for Deal with the Devil, discard up to three cards and redraw.", ""],
  ["dl-edge-whateley-blood", "Whateley Blood", "Arcane", "Novice", "Arcane Background (Huckster)", "Has an unsettling bloodline: social penalty to Persuasion. Can suffer Fatigue for 5 Power Points or a Wound for 10 Power Points as a free action.", ""],
  ["dl-edge-alchemy", "Alchemy", "Arcane", "Seasoned", "Arcane Background (Mad Scientist), Weird Science d8+", "Creates up to three short-lived potions/elixirs, each tying up one Power Point and costing reagents. Potion options cover healing, Trait boost, or Fatigue relief.", ""],
  ["dl-edge-iron-bound", "Iron Bound", "Arcane", "Novice", "Arcane Background (Mad Scientist)", "Starts with a large budget in infernal devices or vehicles and gets a discount from the relevant source later.", ""],
  ["dl-edge-ore-eater", "Ore Eater", "Arcane", "Novice", "Arcane Background (Mad Scientist), Weird Science d6+", "Gains 5 Power Points. Malfunction result 13 becomes ghost rock fever instead of the normal result.", ""],
  ["dl-edge-true-genius", "True Genius", "Arcane", "Novice", "Smarts d8+, Arcane Background (Mad Scientist)", "Spend Bennies to reroll Madness or infernal-device Malfunction Table results, choosing the preferred result.", ""],
  ["dl-edge-fetish", "Fetish", "Arcane", "Novice", "Arcane Background (Shaman), Faith d8+", "Free reroll on Faith rolls while the fetish is available. Replacement can be created with a ritual.", ""],
  ["dl-edge-spirits-favor", "Spirit’s Favor", "Arcane", "Seasoned", "Arcane Background (Shaman), Faith d8+", "Choose one Shaman power each time this Edge is taken. That power can be cast as an action without Multi-Action penalty, once per turn.", "Required"],
  ["dl-edge-lieutenant", "Lieutenant", "Organization", "Seasoned", "Territorial Ranger", "Character is already a Ranger Lieutenant with Chapter 13 knowledge and three Favors.", ""],
  ["dl-edge-like-an-oak", "Like an Oak", "Organization", "Veteran", "Grit, Territorial Ranger", "Allies near the Ranger reduce Fear penalties if the Ranger holds steady. Ranger checks first when the group checks together.", ""],
].map(([id, name, category, rank, requirements, shortSummary, subchoice]) => ({
  id,
  name,
  type: "edge",
  category,
  rank,
  requirements,
  shortSummary,
  source: "Deadlands: The Weird West",
  subchoice,
  isCustom: false,
}));


const SWADE_CORE_HINDRANCE_CATALOG = [
  ["swade-hindrance-all-thumbs","All Thumbs","Minor","-2 to use mechanical or electrical devices."],
  ["swade-hindrance-anemic","Anemic","Minor","-2 Vigor when resisting Fatigue."],
  ["swade-hindrance-arrogant","Arrogant","Major","Tries to dominate rivals and challenge the strongest foe."],
  ["swade-hindrance-bad-eyes","Bad Eyes","Minor or Major","Penalty to Trait rolls dependent on vision; eyewear can negate but may break."],
  ["swade-hindrance-bad-luck","Bad Luck","Major","Starts each session with one fewer Benny."],
  ["swade-hindrance-big-mouth","Big Mouth","Minor","Cannot keep secrets and tends to reveal private information."],
  ["swade-hindrance-blind","Blind","Major","Severe penalty to vision-based tasks; grants a free Edge to offset."],
  ["swade-hindrance-bloodthirsty","Bloodthirsty","Major","Does not take prisoners and tends toward lethal solutions."],
  ["swade-hindrance-cant-swim","Can't Swim","Minor","Penalty to swimming rolls and extremely limited swimming Pace."],
  ["swade-hindrance-cautious","Cautious","Minor","Overplans and avoids rash decisions."],
  ["swade-hindrance-clueless","Clueless","Major","Penalty to Common Knowledge and Notice."],
  ["swade-hindrance-clumsy","Clumsy","Major","Penalty to Athletics and Stealth."],
  ["swade-hindrance-code-of-honor","Code of Honor","Major","Keeps their word and acts according to a strict honorable code."],
  ["swade-hindrance-curious","Curious","Major","Compelled to investigate mysteries and unknowns."],
  ["swade-hindrance-death-wish","Death Wish","Minor","Wants to die after or while completing an epic goal."],
  ["swade-hindrance-delusional","Delusional","Minor or Major","Believes something false or strange that causes trouble."],
  ["swade-hindrance-doubting-thomas","Doubting Thomas","Minor","Does not believe in the supernatural and takes unnecessary risks around it."],
  ["swade-hindrance-driven","Driven","Minor or Major","Has a major goal or belief that drives choices."],
  ["swade-hindrance-elderly","Elderly","Major","Physical penalties but extra skill points at creation."],
  ["swade-hindrance-enemy","Enemy","Minor or Major","Has a recurring nemesis or hostile group."],
  ["swade-hindrance-greedy","Greedy","Minor or Major","Obsessed with wealth or possessions."],
  ["swade-hindrance-habit","Habit","Minor or Major","Addiction or dependency; deprivation can cause Fatigue."],
  ["swade-hindrance-hard-of-hearing","Hard of Hearing","Minor or Major","Penalty to Notice sounds, or automatic failure if deaf."],
  ["swade-hindrance-heroic","Heroic","Major","Always helps those in need, even at personal risk."],
  ["swade-hindrance-hesitant","Hesitant","Minor","Draws two Action Cards and takes the lowest, except Jokers."],
  ["swade-hindrance-illiterate","Illiterate","Minor","Cannot read or write."],
  ["swade-hindrance-impulsive","Impulsive","Major","Acts before thinking and jumps into danger."],
  ["swade-hindrance-jealous","Jealous","Minor or Major","Covets what others have."],
  ["swade-hindrance-loyal","Loyal","Minor","Loyal to friends and allies, even when costly."],
  ["swade-hindrance-mean","Mean","Minor","-1 to Persuasion rolls."],
  ["swade-hindrance-mild-mannered","Mild Mannered","Minor","-2 to Intimidation rolls."],
  ["swade-hindrance-mute","Mute","Major","Cannot speak."],
  ["swade-hindrance-obese","Obese","Minor","Size +1, Pace -1, running die d4, and lower effective Strength for Minimum Strength checks."],
  ["swade-hindrance-obligation","Obligation","Minor or Major","Owes regular weekly time or service to someone or something."],
  ["swade-hindrance-one-arm","One Arm","Major","-4 to tasks requiring two hands."],
  ["swade-hindrance-one-eye","One Eye","Major","-2 to actions at 5 inches / 10 yards or more."],
  ["swade-hindrance-outsider","Outsider","Minor or Major","Does not fit local society; Persuasion penalty and possible legal/social limits."],
  ["swade-hindrance-overconfident","Overconfident","Major","Believes they can handle anything."],
  ["swade-hindrance-pacifist","Pacifist","Minor or Major","Minor fights only in self-defense; Major will not fight at all."],
  ["swade-hindrance-phobia","Phobia","Minor or Major","Trait penalty in the presence of the feared thing."],
  ["swade-hindrance-poverty","Poverty","Minor","Half starting funds and tends to stay broke."],
  ["swade-hindrance-quirk","Quirk","Minor","Persistent minor foible that annoys or complicates things."],
  ["swade-hindrance-ruthless","Ruthless","Minor or Major","Does what it takes to get their way."],
  ["swade-hindrance-secret","Secret","Minor or Major","Has a dark secret that can cause trouble if revealed."],
  ["swade-hindrance-shamed","Shamed","Minor or Major","Haunted by a past tragedy or failure."],
  ["swade-hindrance-slow","Slow","Minor or Major","Reduced Pace and running die; Major also penalizes Athletics and resisting Athletics."],
  ["swade-hindrance-small","Small","Minor","Size and Toughness reduced by 1."],
  ["swade-hindrance-stubborn","Stubborn","Minor","Insists on their own way and rarely admits mistakes."],
  ["swade-hindrance-suspicious","Suspicious","Minor or Major","Paranoid; Major penalizes Support rolls to aid them."],
  ["swade-hindrance-thin-skinned","Thin Skinned","Minor or Major","Penalty when resisting Taunt attacks."],
  ["swade-hindrance-tongue-tied","Tongue-Tied","Major","Penalty to speech-based Intimidation, Performance, Persuasion, and Taunt."],
  ["swade-hindrance-ugly","Ugly","Minor or Major","Penalty to Persuasion due to appearance."],
  ["swade-hindrance-vengeful","Vengeful","Minor or Major","Seeks payback; Major escalates to physical harm."],
  ["swade-hindrance-vow","Vow","Minor or Major","Sworn oath or cause that creates obligations and risk."],
  ["swade-hindrance-wanted","Wanted","Minor or Major","Wanted by authorities or enemies."],
  ["swade-hindrance-yellow","Yellow","Major","-2 to Fear checks and resisting Intimidation."],
  ["swade-hindrance-young","Young","Minor or Major","Reduced starting attribute/skill points but extra Bennies."]
].map(([id, name, severity, shortSummary]) => ({
  id,
  name,
  type: "hindrance",
  severity,
  shortSummary,
  source: "Savage Worlds Adventure Edition",
  isCustom: false,
  settingAvailability: { swadeCore: true, deadlandsWeirdWest: true },
}));

const SWADE_CORE_EDGE_CATALOG = [
  ["swade-edge-alertness","Alertness","Background","Novice","Novice","+2 to Notice rolls.","",true],
  ["swade-edge-ambidextrous","Ambidextrous","Background","Novice","Novice, Agility d8+","Ignore the off-hand penalty when making Trait rolls.","",true],
  ["swade-edge-arcane-background","Arcane Background","Background","Novice","Novice","Allows access to an Arcane Background from the core rules.","",false],
  ["swade-edge-arcane-resistance","Arcane Resistance","Background","Novice","Novice, Spirit d8+","+2 to resist magical effects; magical damage reduced by 2.","",true],
  ["swade-edge-improved-arcane-resistance","Improved Arcane Resistance","Background","Novice","Novice, Arcane Resistance","+4 to resist magical effects; magical damage reduced by 4.","",true],
  ["swade-edge-aristocrat","Aristocrat","Background","Novice","Novice","+2 to Common Knowledge and networking with the upper class.","",true],
  ["swade-edge-attractive","Attractive","Background","Novice","Novice, Vigor d6+","+1 to Performance and Persuasion when appearance matters.","",true],
  ["swade-edge-very-attractive","Very Attractive","Background","Novice","Novice, Attractive","+2 to Performance and Persuasion when appearance matters.","",true],
  ["swade-edge-berserk","Berserk","Background","Novice","Novice","After being Shaken or Wounded, enters a rage with stronger melee offense and toughness but risks uncontrolled attacks.","",true],
  ["swade-edge-brave","Brave","Background","Novice","Novice, Spirit d6+","+2 to Fear checks and -2 on Fear Table rolls.","",true],
  ["swade-edge-brawny","Brawny","Background","Novice","Novice, Strength d6+, Vigor d6+","Size and Toughness +1; Strength counts one die higher for Encumbrance and Minimum Strength.","",true],
  ["swade-edge-brute","Brute","Background","Novice","Novice, Strength d6+, Vigor d6+","Athletics links to Strength instead of Agility and thrown ranges improve.","",true],
  ["swade-edge-charismatic","Charismatic","Background","Novice","Novice, Spirit d8+","Free reroll when using Persuasion.","",true],
  ["swade-edge-elan","Elan","Background","Novice","Novice, Spirit d8+","+2 when spending a Benny to reroll a Trait roll.","",true],
  ["swade-edge-fame","Fame","Background","Novice","Novice","+1 Persuasion when recognized and better Performance pay.","",true],
  ["swade-edge-famous","Famous","Background","Seasoned","Seasoned, Fame","+2 Persuasion when recognized and much better Performance pay.","",true],
  ["swade-edge-fast-healer","Fast Healer","Background","Novice","Novice, Vigor d8+","+2 to natural healing rolls and checks more often.","",true],
  ["swade-edge-fleet-footed","Fleet-Footed","Background","Novice","Novice, Agility d6+","Pace +2 and running die increases one step.","",true],
  ["swade-edge-linguist","Linguist","Background","Novice","Novice, Smarts d6+","Knows extra languages based on Smarts.","",true],
  ["swade-edge-luck","Luck","Background","Novice","Novice","+1 Benny at the start of each session.","",true],
  ["swade-edge-great-luck","Great Luck","Background","Novice","Novice, Luck","+2 Bennies at the start of each session.","",true],
  ["swade-edge-quick","Quick","Background","Novice","Novice, Agility d8+","May discard and redraw Action Cards of 5 or lower.","",true],
  ["swade-edge-rich","Rich","Background","Novice","Novice","Starts with triple funds and a strong income.","",true],
  ["swade-edge-filthy-rich","Filthy Rich","Background","Novice","Novice, Rich","Starts with five times funds and a much higher income.","",true],
  ["swade-edge-block","Block","Combat","Seasoned","Seasoned, Fighting d8+","+1 Parry and ignore 1 point of Gang Up bonus.","",true],
  ["swade-edge-improved-block","Improved Block","Combat","Veteran","Veteran, Block","+2 Parry and ignore 2 points of Gang Up bonus.","",true],
  ["swade-edge-brawler","Brawler","Combat","Novice","Novice, Strength d8+, Vigor d8+","+1 Toughness and improved unarmed damage.","",true],
  ["swade-edge-bruiser","Bruiser","Combat","Seasoned","Seasoned, Brawler","Further improves unarmed damage and Toughness.","",true],
  ["swade-edge-calculating","Calculating","Combat","Novice","Novice, Smarts d8+","Ignore up to 2 points of penalties on one action with low Action Card.","",true],
  ["swade-edge-combat-reflexes","Combat Reflexes","Combat","Seasoned","Seasoned","+2 Spirit to recover from being Shaken or Stunned.","",true],
  ["swade-edge-counterattack","Counterattack","Combat","Seasoned","Seasoned, Fighting d8+","Free attack against one foe per turn who failed a Fighting roll.","",true],
  ["swade-edge-improved-counterattack","Improved Counterattack","Combat","Veteran","Veteran, Counterattack","Counterattack works against up to three foes per turn.","",true],
  ["swade-edge-dead-shot","Dead Shot","Combat","Novice","Wild Card, Novice, Athletics or Shooting d8+","Once per turn, double ranged or thrown damage when dealt a Joker.","",true],
  ["swade-edge-dodge","Dodge","Combat","Seasoned","Seasoned, Agility d8+","-2 to be hit by ranged attacks.","",true],
  ["swade-edge-improved-dodge","Improved Dodge","Combat","Seasoned","Seasoned, Dodge","+2 to Evasion totals.","",true],
  ["swade-edge-double-tap","Double Tap","Combat","Seasoned","Seasoned, Shooting d6+","+1 to hit and damage when firing no more than RoF 1 per action.","",true],
  ["swade-edge-extraction","Extraction","Combat","Novice","Novice, Agility d8+","One adjacent foe does not get a free attack when you withdraw.","",true],
  ["swade-edge-improved-extraction","Improved Extraction","Combat","Seasoned","Seasoned, Extraction","Up to three adjacent foes do not get free attacks when you withdraw.","",true],
  ["swade-edge-feint","Feint","Combat","Novice","Novice, Fighting d8+","May make a Fighting Test resisted by Smarts instead of Agility.","",true],
  ["swade-edge-first-strike","First Strike","Combat","Novice","Novice, Agility d8+","Free Fighting attack once per round when a foe moves into Reach.","",true],
  ["swade-edge-improved-first-strike","Improved First Strike","Combat","Heroic","Heroic, First Strike","Free Fighting attack against up to three foes moving into Reach.","",true],
  ["swade-edge-free-runner","Free Runner","Combat","Novice","Novice, Agility d8+","Ignore Difficult Ground and gain bonuses in foot chases and climbing.","",true],
  ["swade-edge-frenzy","Frenzy","Combat","Seasoned","Seasoned, Fighting d8+","Roll a second Fighting die for one melee attack as a limited action.","",true],
  ["swade-edge-improved-frenzy","Improved Frenzy","Combat","Veteran","Veteran, Frenzy","Roll a third Fighting die for one melee attack.","",true],
  ["swade-edge-giant-killer","Giant Killer","Combat","Veteran","Veteran","+1d6 damage against creatures three Sizes larger.","",true],
  ["swade-edge-hard-to-kill","Hard to Kill","Combat","Novice","Novice, Spirit d8+","Ignore Wound penalties on Vigor rolls to avoid Bleeding Out.","",true],
  ["swade-edge-harder-to-kill","Harder to Kill","Combat","Veteran","Veteran, Hard to Kill","If the character dies, a die roll may let them survive somehow.","",true],
  ["swade-edge-improved-level-headed","Improved Level Headed","Combat","Seasoned","Seasoned, Level Headed","Draw two additional Action Cards each round and choose which to use.","",true],
  ["swade-edge-improved-nerves-of-steel","Improved Nerves of Steel","Combat","Novice","Novice, Nerves of Steel","Ignore up to two levels of Wound penalties.","",true],
  ["swade-edge-improved-rapid-fire","Improved Rapid Fire","Combat","Veteran","Veteran, Rapid Fire","Increase RoF by 1 for up to two Shooting attacks per turn.","",true],
  ["swade-edge-improvisational-fighter","Improvisational Fighter","Combat","Seasoned","Seasoned, Smarts d6+","Ignore the improvised weapon penalty.","",true],
  ["swade-edge-iron-jaw","Iron Jaw","Combat","Novice","Novice, Vigor d8+","+2 to Soak rolls and to avoid Knockout Blows.","",true],
  ["swade-edge-killer-instinct","Killer Instinct","Combat","Seasoned","Seasoned","Free reroll in opposed Tests initiated by the hero.","",true],
  ["swade-edge-level-headed","Level Headed","Combat","Seasoned","Seasoned, Smarts d8+","Draw an additional Action Card each round and choose which to use.","",true],
  ["swade-edge-marksman","Marksman","Combat","Seasoned","Seasoned, Shooting d8+","Ignore up to 2 points of Range, Cover, or Called Shot penalties with RoF 1 weapons.","",true],
  ["swade-edge-martial-artist","Martial Artist","Combat","Novice","Novice, Fighting d6+","Unarmed Fighting +1; fists and feet count as Natural Weapons and add damage.","",true],
  ["swade-edge-martial-warrior","Martial Warrior","Combat","Seasoned","Seasoned, Martial Artist","Unarmed Fighting +2 and further improves unarmed damage.","",true],
  ["swade-edge-mighty-blow","Mighty Blow","Combat","Novice","Wild Card, Novice, Fighting d8+","Once per turn, double Fighting damage when dealt a Joker.","",true],
  ["swade-edge-nerves-of-steel","Nerves of Steel","Combat","Novice","Novice, Vigor d8+","Ignore one level of Wound penalties.","",true],
  ["swade-edge-no-mercy","No Mercy","Combat","Seasoned","Seasoned","+2 damage when spending a Benny to reroll damage.","",true],
  ["swade-edge-rapid-fire","Rapid Fire","Combat","Seasoned","Seasoned, Shooting d6+","Increase RoF by 1 for one Shooting attack per turn.","",true],
  ["swade-edge-rock-and-roll","Rock and Roll!","Combat","Seasoned","Seasoned, Shooting d8+","Ignore Recoil penalty when firing weapons with RoF 2 or more.","",true],
  ["swade-edge-steady-hands","Steady Hands","Combat","Novice","Novice, Agility d8+","Ignore Unstable Platform penalty and reduce running penalty.","",true],
  ["swade-edge-sweep","Sweep","Combat","Novice","Novice, Strength d8+, Fighting d8+","Fighting roll at -2 to hit all targets in weapon Reach once per turn.","",true],
  ["swade-edge-improved-sweep","Improved Sweep","Combat","Veteran","Veteran, Sweep","Sweep without the -2 penalty.","",true],
  ["swade-edge-trademark-weapon","Trademark Weapon","Combat","Novice","Novice, relevant weapon skill d8","+1 attack and Parry with a specific weapon.","",true],
  ["swade-edge-improved-trademark-weapon","Improved Trademark Weapon","Combat","Seasoned","Seasoned, Trademark Weapon","Trademark Weapon bonus increases to +2.","",true],
  ["swade-edge-two-fisted","Two-Fisted","Combat","Novice","Novice, Agility d8+","Extra Fighting roll with a second melee weapon in the off-hand at no Multi-Action penalty.","",true],
  ["swade-edge-two-gun-kid","Two-Gun Kid","Combat","Novice","Novice, Agility d8+","Extra Shooting or throwing roll with a second ranged weapon in the off-hand at no Multi-Action penalty.","",true],
  ["swade-edge-command","Command","Leadership","Novice","Novice, Smarts d6+","+1 to Extras' Shaken recovery rolls in Command Range.","",true],
  ["swade-edge-command-presence","Command Presence","Leadership","Seasoned","Seasoned, Command","Command Range increases to 10 inches / 20 yards.","",true],
  ["swade-edge-fervor","Fervor","Leadership","Veteran","Veteran, Spirit d8+, Command","+1 to Extras' Fighting rolls in Command Range.","",true],
  ["swade-edge-hold-the-line","Hold the Line!","Leadership","Seasoned","Seasoned, Smarts d8+, Command","+1 Toughness to Extras in Command Range.","",true],
  ["swade-edge-inspire","Inspire","Leadership","Seasoned","Seasoned, Command","Battle roll Supports a chosen Trait roll for everyone in Command Range.","",true],
  ["swade-edge-natural-leader","Natural Leader","Leadership","Seasoned","Seasoned, Spirit d8+, Command","Leadership Edges apply to Wild Cards as well as Extras.","",true],
  ["swade-edge-tactician","Tactician","Leadership","Seasoned","Seasoned, Smarts d8+, Command, Battle d6+","Draw an extra Action Card each turn and assign it to an allied Extra.","",true],
  ["swade-edge-master-tactician","Master Tactician","Leadership","Veteran","Veteran, Tactician","Draw and distribute two extra Action Cards instead of one.","",true],
  ["swade-edge-artificer","Artificer","Arcane","Seasoned","Seasoned, Arcane Background","Allows creation of Arcane Devices.","",true],
  ["swade-edge-channeling","Channeling","Arcane","Seasoned","Seasoned, Arcane Background","Reduce Power Point cost by 1 with a raise on activation.","",true],
  ["swade-edge-concentration","Concentration","Arcane","Seasoned","Seasoned, Arcane Background","Shaken results do not cause Disruption; Stun or Wounds still can.","",true],
  ["swade-edge-extra-effort","Extra Effort","Arcane","Seasoned","Seasoned, Arcane Background (Gifted), Focus d6+","Spend Power Points to temporarily increase Focus.","",true],
  ["swade-edge-gadgeteer","Gadgeteer","Arcane","Seasoned","Seasoned, Arcane Background (Weird Science), Weird Science d6+","Spend 3 Power Points to create a device that replicates another power.","",true],
  ["swade-edge-holy-unholy-warrior","Holy/Unholy Warrior","Arcane","Seasoned","Seasoned, Arcane Background (Miracles), Faith d6+","Spend Power Points for a Soak bonus.","",true],
  ["swade-edge-mentalist","Mentalist","Arcane","Seasoned","Seasoned, Arcane Background (Psionics), Psionics d6+","+2 to opposed Psionics rolls.","",true],
  ["swade-edge-new-powers","New Powers","Arcane","Novice","Novice, Arcane Background","Learn two new powers.","",true],
  ["swade-edge-power-points","Power Points","Arcane","Novice","Novice, Arcane Background","Gain 5 additional Power Points, no more than once per Rank.","",true],
  ["swade-edge-power-surge","Power Surge","Arcane","Novice","Wild Card, Novice, Arcane Background, arcane skill d8+","Recover 10 Power Points when dealt a Joker in combat.","",true],
  ["swade-edge-rapid-recharge","Rapid Recharge","Arcane","Seasoned","Seasoned, Spirit d6+, Arcane Background","Recover 10 Power Points per hour.","",true],
  ["swade-edge-improved-rapid-recharge","Improved Rapid Recharge","Arcane","Veteran","Veteran, Rapid Recharge","Recover 20 Power Points per hour.","",true],
  ["swade-edge-soul-drain","Soul Drain","Arcane","Seasoned","Seasoned, Arcane Background, arcane skill d10+","Recover 5 Power Points for a level of Fatigue.","",false],
  ["swade-edge-wizard","Wizard","Arcane","Seasoned","Seasoned, Arcane Background (Magic), Spellcasting d6+","Spend 1 extra Power Point to change a spell's Trapping.","",true],
  ["swade-edge-ace","Ace","Professional","Novice","Novice, Agility d8+","Spend Bennies to Soak vehicle damage and ignore up to 2 points of vehicle operation penalties.","",true],
  ["swade-edge-acrobat","Acrobat","Professional","Novice","Novice, Agility d8+, Athletics d8+","Free reroll on acrobatic Athletics attempts.","",true],
  ["swade-edge-combat-acrobat","Combat Acrobat","Professional","Seasoned","Seasoned, Acrobat","Attacks against the character suffer -1 when they can move freely.","",true],
  ["swade-edge-assassin","Assassin","Professional","Novice","Novice, Agility d8+, Fighting d6+, Stealth d8+","+2 damage against Vulnerable foes or when the assassin has The Drop.","",true],
  ["swade-edge-investigator","Investigator","Professional","Novice","Novice, Smarts d8+, Research d8+","+2 to Research and clue-related Notice rolls.","",true],
  ["swade-edge-jack-of-all-trades","Jack-of-All-Trades","Professional","Novice","Novice, Smarts d10+","Temporarily gains d4 in an untrained Smarts-based skill, or d6 with a raise.","",true],
  ["swade-edge-mcgyver","McGyver","Professional","Novice","Novice, Smarts d6+, Repair d6+, Notice d8+","Quickly creates improvised devices from available scraps.","",true],
  ["swade-edge-mr-fix-it","Mr. Fix It","Professional","Novice","Novice, Repair d8+","+2 to Repair rolls; repairs take less time with a raise.","",true],
  ["swade-edge-scholar","Scholar","Professional","Novice","Novice, Research d8+","+2 to one knowledge-related skill.","",true],
  ["swade-edge-soldier","Soldier","Professional","Novice","Novice, Strength d6+, Vigor d6+","Strength counts one die higher for Encumbrance and Minimum Strength; reroll Vigor against environmental Hazards.","",true],
  ["swade-edge-thief","Thief","Professional","Novice","Novice, Agility d8+, Stealth d6+, Thievery d6+","+1 to Thievery, climbing Athletics, and urban Stealth.","",true],
  ["swade-edge-woodsman","Woodsman","Professional","Novice","Novice, Spirit d6+, Survival d8+","+2 to Survival and wilderness Stealth.","",true],
  ["swade-edge-bolster","Bolster","Social","Novice","Novice, Spirit d8+","After a successful Test, remove Distracted or Vulnerable from an ally.","",true],
  ["swade-edge-common-bond","Common Bond","Social","Novice","Wild Card, Novice, Spirit d8+","May freely give Bennies to other characters.","",true],
  ["swade-edge-connections","Connections","Social","Novice","Novice","Has contacts who can provide aid or favors once per session.","",true],
  ["swade-edge-humiliate","Humiliate","Social","Novice","Novice, Taunt d8+","Free reroll when making Taunt Tests.","",true],
  ["swade-edge-menacing","Menacing","Social","Novice","Novice, Bloodthirsty / Mean / Ruthless / Ugly","+2 to Intimidation using bad looks or attitude.","",true],
  ["swade-edge-provoke","Provoke","Social","Novice","Novice, Taunt d6+","With a raise on Taunt, make the target worse at affecting others.","",true],
  ["swade-edge-rabble-rouser","Rabble-Rouser","Social","Seasoned","Seasoned, Spirit d8+","Intimidation or Taunt Test against all foes in a Medium Blast Template once per turn.","",true],
  ["swade-edge-reliable","Reliable","Social","Novice","Novice, Spirit d8+","Free reroll when making Support rolls.","",true],
  ["swade-edge-retort","Retort","Social","Novice","Novice, Taunt d6+","A raise when resisting Taunt or Intimidation makes the foe Distracted.","",true],
  ["swade-edge-streetwise","Streetwise","Social","Novice","Novice, Smarts d6+","+2 to Common Knowledge and criminal networking.","",true],
  ["swade-edge-strong-willed","Strong Willed","Social","Novice","Novice, Spirit d8+","+2 to resist Smarts or Spirit-based Tests.","",true],
  ["swade-edge-iron-will","Iron Will","Social","Novice","Novice, Strong Willed","+4 to resist Smarts or Spirit-based Tests.","",true],
  ["swade-edge-work-the-room","Work the Room","Social","Novice","Novice, Spirit d8+","Roll a second die when Supporting via Performance or Persuasion and apply it to another ally.","",true],
  ["swade-edge-work-the-crowd","Work the Crowd","Social","Seasoned","Seasoned, Work the Room","Work the Room can apply to up to two additional allies.","",true],
  ["swade-edge-beast-bond","Beast Bond","Weird","Novice","Novice","May spend Bennies for animals under the hero's control.","",true],
  ["swade-edge-beast-master","Beast Master","Weird","Novice","Novice, Spirit d8+","Animals like the hero and the hero has a pet, subject to GM approval.","",true],
  ["swade-edge-champion","Champion","Weird","Novice","Novice, Spirit d8+, Fighting d6+","+2 damage versus supernaturally evil creatures.","",true],
  ["swade-edge-chi","Chi","Weird","Veteran","Veteran, Martial Warrior","Once per combat, use a Chi Point to reroll an attack, force an enemy attack reroll, or add damage to an unarmed attack.","",true],
  ["swade-edge-danger-sense","Danger Sense","Weird","Novice","Novice","Notice roll at +2 to sense ambushes or similar danger.","",true],
  ["swade-edge-healer","Healer","Weird","Novice","Novice, Spirit d8+","+2 to Healing rolls, magical or mundane.","",true],
  ["swade-edge-liquid-courage","Liquid Courage","Weird","Novice","Novice, Vigor d8+","Alcohol boosts Vigor and ignores one Wound penalty level, but penalizes Agility, Smarts, and linked skills.","",true],
  ["swade-edge-scavenger","Scavenger","Weird","Novice","Novice, Luck","Once per encounter, find or remember a needed item or resource.","",true],
  ["swade-edge-followers","Followers","Legendary","Legendary","Wild Card, Legendary","Gain five loyal followers.","",true],
  ["swade-edge-professional","Professional","Legendary","Legendary","Legendary, d12 in Trait","Chosen Trait and its limit increase one step.","",true],
  ["swade-edge-expert","Expert","Legendary","Legendary","Legendary, Professional in Trait","Chosen Trait and its limit increase one additional step.","",true],
  ["swade-edge-master","Master","Legendary","Legendary","Wild Card, Legendary, Expert in Trait","Wild Die becomes d10 with the chosen Trait.","",true],
  ["swade-edge-sidekick","Sidekick","Legendary","Legendary","Wild Card, Legendary","Gain a Novice Rank Wild Card sidekick.","",true],
  ["swade-edge-tough-as-nails","Tough as Nails","Legendary","Legendary","Legendary, Vigor d8+","Can take four Wounds before Incapacitation.","",true],
  ["swade-edge-tougher-than-nails","Tougher than Nails","Legendary","Legendary","Legendary, Tough as Nails, Vigor d12+","Can take five Wounds before Incapacitation.","",true],
  ["swade-edge-weapon-master","Weapon Master","Legendary","Legendary","Legendary, Fighting d12+","Parry +1 and Fighting bonus damage die becomes d8.","",true],
  ["swade-edge-master-of-arms","Master of Arms","Legendary","Legendary","Legendary, Weapon Master","Additional Parry +1 and Fighting bonus damage die becomes d10.","",true]
].map(
  ([id, name, category, rank, requirements, shortSummary, subchoice, deadlandsWeirdWest]) => ({
    id,
    name,
    type: "edge",
    category,
    rank,
    requirements,
    shortSummary,
    source: "Savage Worlds Adventure Edition",
    subchoice,
    isCustom: false,
    settingAvailability: {
      swadeCore: true,
      deadlandsWeirdWest,
      reason: deadlandsWeirdWest
        ? ""
        : name === "Soul Drain"
          ? "Deadlands specifically excludes Soul Drain."
          : "Deadlands replaces this with setting-specific Arcane Background rules.",
    },
  }),
);

const HINDRANCE_CATALOG = [
  ...SWADE_CORE_HINDRANCE_CATALOG,
  ...DEADLANDS_HINDRANCE_CATALOG,
];

const EDGE_CATALOG = [
  ...SWADE_CORE_EDGE_CATALOG.filter(
    (edge) => edge.settingAvailability?.deadlandsWeirdWest !== false,
  ),
  ...DEADLANDS_EDGE_CATALOG,
];

const GEAR_CATALOG = [
  {
    id: "winter-coat",
    name: "Winter coat",
    book: "Deadlands",
    weight: 3,
    costCents: 1500,
  },
  {
    id: "watch-standard",
    name: "Watch, standard",
    book: "Deadlands",
    weight: 0.5,
    costCents: 250,
  },
  {
    id: "watch-gold",
    name: "Watch, gold",
    book: "Deadlands",
    weight: 0.5,
    costCents: 1000,
  },
  {
    id: "vocal-unction-elixir",
    name: "Vocal unction elixir",
    book: "Deadlands",
    weight: 0,
    costCents: 5000,
  },
  {
    id: "vapor-mask",
    name: "Vapor mask",
    book: "Deadlands",
    weight: 0.5,
    costCents: 10000,
  },
  {
    id: "trousers-skirt",
    name: "Trousers/skirt",
    book: "Deadlands",
    weight: 2,
    costCents: 200,
  },
  {
    id: "trail-rations-per-day",
    name: "Trail Rations (per day)",
    book: "Deadlands",
    weight: 3,
    costCents: 50,
  },
  {
    id: "tool-kit-weird-science",
    name: "Tool Kit (Weird Science)",
    book: "Deadlands",
    weight: 5,
    costCents: 5000,
  },
  {
    id: "tool-kit",
    name: "Tool kit",
    book: "Deadlands",
    weight: 5,
    costCents: 2500,
  },
  {
    id: "tobacco-smoking-pouch",
    name: "Tobacco, smoking (pouch)",
    book: "Deadlands",
    weight: 1,
    costCents: 50,
  },
  {
    id: "tobacco-chewing-tin",
    name: "Tobacco, chewing (tin)",
    book: "Deadlands",
    weight: 1,
    costCents: 50,
  },
  {
    id: "tactile-desensitizer",
    name: "Tactile desensitizer",
    book: "Deadlands",
    weight: 0,
    costCents: 3000,
  },
  {
    id: "suit-fancy-dress",
    name: "Suit/fancy dress",
    book: "Deadlands",
    weight: 6,
    costCents: 1500,
  },
  {
    id: "stetson",
    name: "Stetson",
    book: "Deadlands",
    weight: 0,
    costCents: 500,
  },
  {
    id: "spring-boots",
    name: "Spring Boots",
    book: "Deadlands",
    weight: 2,
    costCents: 40000,
  },
  {
    id: "speed-load-cylinder",
    name: "Speed-load cylinder",
    book: "Deadlands",
    weight: 0.25,
    costCents: 300,
  },
  {
    id: "spectacles",
    name: "Spectacles",
    book: "Deadlands",
    weight: 0,
    costCents: 500,
  },
  {
    id: "sombrero",
    name: "Sombrero",
    book: "Deadlands",
    weight: 0,
    costCents: 350,
  },
  {
    id: "silver-ore",
    name: "Silver ore",
    book: "Deadlands",
    weight: 1,
    costCents: 2400,
  },
  {
    id: "silk-stockings",
    name: "Silk Stockings",
    book: "Deadlands",
    weight: 0,
    costCents: 100,
  },
  {
    id: "shovel",
    name: "Shovel",
    book: "Deadlands",
    weight: 5,
    costCents: 150,
  },
  {
    id: "shotgun-thong",
    name: "Shotgun thong",
    book: "Deadlands",
    weight: 0,
    costCents: 25,
  },
  {
    id: "shotgun-shells",
    name: "Shotgun shells",
    book: "Deadlands",
    weight: 0.1,
    costCents: 10,
  },
  {
    id: "shot-w-powder",
    name: "Shot w/powder",
    book: "Deadlands",
    weight: 0.2,
    costCents: 5,
  },
  {
    id: "shoes",
    name: "Shoes",
    book: "Deadlands",
    weight: 1,
    costCents: 200,
  },
  {
    id: "shirt-blouse-work",
    name: "Shirt/blouse, work",
    book: "Deadlands",
    weight: 1,
    costCents: 100,
  },
  {
    id: "shirt-blouse-dress",
    name: "Shirt/blouse, dress",
    book: "Deadlands",
    weight: 1,
    costCents: 300,
  },
  {
    id: "scope",
    name: "Scope",
    book: "Deadlands",
    weight: 2,
    costCents: 3000,
  },
  {
    id: "samson-s-elixir",
    name: "Samson's elixir",
    book: "Deadlands",
    weight: 0,
    costCents: 6000,
  },
  {
    id: "saddlebags",
    name: "Saddlebags",
    book: "Deadlands",
    weight: 5,
    costCents: 500,
  },
  {
    id: "saddle",
    name: "Saddle",
    book: "Deadlands",
    weight: 30,
    costCents: 2500,
  },
  {
    id: "rope-10",
    name: 'Rope (10")',
    book: "Deadlands",
    weight: 8,
    costCents: 500,
  },
  {
    id: "rifle-boot",
    name: "Rifle Boot",
    book: "Deadlands",
    weight: 0.5,
    costCents: 300,
  },
  {
    id: "rifle-ammunition-small-38-44-caliber",
    name: "Rifle Ammunition (Small, .38-.44 caliber)",
    book: "Deadlands",
    weight: 0.12,
    costCents: 8,
  },
  {
    id: "rifle-ammunition-large-50-caliber",
    name: "Rifle Ammunition (Large, .50+ caliber)",
    book: "Deadlands",
    weight: 0.16,
    costCents: 10,
  },
  {
    id: "restoration-elixir",
    name: "Restoration elixir",
    book: "Deadlands",
    weight: 0,
    costCents: 10000,
  },
  {
    id: "refined-ghost-rock",
    name: "Refined Ghost Rock",
    book: "Deadlands",
    weight: 1,
    costCents: 15000,
  },
  {
    id: "rattler-detector",
    name: "Rattler detector",
    book: "Deadlands",
    weight: 5,
    costCents: 10000,
  },
  {
    id: "quick-draw-holster",
    name: "Quick-draw holster",
    book: "Deadlands",
    weight: 1,
    costCents: 1100,
  },
  {
    id: "powered-de-moler",
    name: "Powered De-Moler",
    book: "Deadlands",
    weight: 5,
    costCents: 12000,
  },
  {
    id: "playing-cards",
    name: "Playing cards",
    book: "Deadlands",
    weight: 0,
    costCents: 25,
  },
  {
    id: "pistol-ammunition-small-22-38-caliber",
    name: "Pistol Ammunition (Small, .22-.38 caliber)",
    book: "Deadlands",
    weight: 0.06,
    costCents: 4,
  },
  {
    id: "pistol-ammunition-large-40-50-caliber",
    name: "Pistol Ammunition (Large, .40-.50 caliber)",
    book: "Deadlands",
    weight: 0.1,
    costCents: 6,
  },
  {
    id: "pipe",
    name: "Pipe",
    book: "Deadlands",
    weight: 0.75,
    costCents: 200,
  },
  {
    id: "pick",
    name: "Pick",
    book: "Deadlands",
    weight: 12,
    costCents: 200,
  },
  {
    id: "percussion-caps",
    name: "Percussion caps",
    book: "Deadlands",
    weight: 0.17,
    costCents: 1,
  },
  {
    id: "owl-eye-goggles",
    name: "Owl-eye goggles",
    book: "Deadlands",
    weight: 1,
    costCents: 60000,
  },
  {
    id: "noiseless-shoes",
    name: "Noiseless Shoes",
    book: "Deadlands",
    weight: 0,
    costCents: 50000,
  },
  {
    id: "mule",
    name: "Mule",
    book: "Deadlands",
    weight: 0,
    costCents: 5000,
  },
  {
    id: "mess-kit",
    name: "Mess kit",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "mechanical-mule",
    name: "Mechanical mule",
    book: "Deadlands",
    weight: 800,
    costCents: 150000,
  },
  {
    id: "matches-box-100",
    name: "Matches (box 100)",
    book: "Deadlands",
    weight: 0.25,
    costCents: 50,
  },
  {
    id: "longjohns",
    name: "Longjohns",
    book: "Deadlands",
    weight: 2,
    costCents: 200,
  },
  {
    id: "lockpicks",
    name: "Lockpicks",
    book: "Deadlands",
    weight: 1,
    costCents: 500,
  },
  {
    id: "liquid-courage",
    name: "Liquid courage",
    book: "Deadlands",
    weight: 0,
    costCents: 3000,
  },
  {
    id: "lantern-oil-per-gallon",
    name: "Lantern oil (per gallon)",
    book: "Deadlands",
    weight: 6,
    costCents: 10,
  },
  {
    id: "lantern",
    name: "Lantern",
    book: "Deadlands",
    weight: 4,
    costCents: 250,
  },
  {
    id: "iron-skillet",
    name: "Iron Skillet",
    book: "Deadlands",
    weight: 5,
    costCents: 50,
  },
  {
    id: "horse",
    name: "Horse",
    book: "Deadlands",
    weight: 0,
    costCents: 15000,
  },
  {
    id: "holster",
    name: "Holster",
    book: "Deadlands",
    weight: 1,
    costCents: 300,
  },
  {
    id: "healing-unguent",
    name: "Healing unguent",
    book: "Deadlands",
    weight: 0,
    costCents: 8000,
  },
  {
    id: "hatchet",
    name: "Hatchet",
    book: "Deadlands",
    weight: 2.5,
    costCents: 100,
  },
  {
    id: "hat-periscope",
    name: "Hat Periscope",
    book: "Deadlands",
    weight: 12,
    costCents: 20000,
  },
  {
    id: "harmonica",
    name: "Harmonica",
    book: "Deadlands",
    weight: 0,
    costCents: 50,
  },
  {
    id: "handcuffs",
    name: "Handcuffs",
    book: "Deadlands",
    weight: 3,
    costCents: 350,
  },
  {
    id: "hammer",
    name: "Hammer",
    book: "Deadlands",
    weight: 2,
    costCents: 50,
  },
  {
    id: "gun-belt",
    name: "Gun belt",
    book: "Deadlands",
    weight: 1,
    costCents: 200,
  },
  {
    id: "guitar",
    name: "Guitar",
    book: "Deadlands",
    weight: 6,
    costCents: 800,
  },
  {
    id: "greased-lightning-pill",
    name: "Greased lightning pill",
    book: "Deadlands",
    weight: 0,
    costCents: 7500,
  },
  {
    id: "gold-ore",
    name: "Gold ore",
    book: "Deadlands",
    weight: 1,
    costCents: 32000,
  },
  {
    id: "ghost-rock-ore",
    name: "Ghost rock ore",
    book: "Deadlands",
    weight: 1,
    costCents: 10000,
  },
  {
    id: "gatling-shotgun-ammo-drum",
    name: "Gatling Shotgun Ammo Drum",
    book: "Deadlands",
    weight: 3.5,
    costCents: 500,
  },
  {
    id: "gatling-rifle-ammo-drum",
    name: "Gatling Rifle Ammo Drum",
    book: "Deadlands",
    weight: 7,
    costCents: 500,
  },
  {
    id: "gatling-pistol-ammo-drum",
    name: "Gatling Pistol Ammo Drum",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "gatling-carbine-ammo-drum",
    name: "Gatling Carbine Ammo Drum",
    book: "Deadlands",
    weight: 7,
    costCents: 500,
  },
  {
    id: "fuse-per-foot",
    name: "Fuse (per foot)",
    book: "Deadlands",
    weight: 0.1,
    costCents: 5,
  },
  {
    id: "file",
    name: "File",
    book: "Deadlands",
    weight: 1,
    costCents: 25,
  },
  {
    id: "fedora",
    name: "Fedora",
    book: "Deadlands",
    weight: 0,
    costCents: 300,
  },
  {
    id: "epitaph-camera",
    name: "Epitaph camera",
    book: "Deadlands",
    weight: 7,
    costCents: 160000,
  },
  {
    id: "electrostatic-belt",
    name: "Electrostatic belt",
    book: "Deadlands",
    weight: 7,
    costCents: 150000,
  },
  {
    id: "dynamite-plinger-3",
    name: "Dynamite Plinger (3)",
    book: "Deadlands",
    weight: 0,
    costCents: 2000,
  },
  {
    id: "duster",
    name: "Duster",
    book: "Deadlands",
    weight: 4,
    costCents: 1000,
  },
  {
    id: "drill",
    name: "Drill",
    book: "Deadlands",
    weight: 2,
    costCents: 200,
  },
  {
    id: "doctor-s-bag",
    name: "Doctor's Bag",
    book: "Deadlands",
    weight: 6,
    costCents: 1000,
  },
  {
    id: "diving-suit",
    name: "Diving Suit",
    book: "Deadlands",
    weight: 45,
    costCents: 200000,
  },
  {
    id: "disguise-kit",
    name: "Disguise kit",
    book: "Deadlands",
    weight: 8,
    costCents: 1000,
  },
  {
    id: "detonator-plunger",
    name: "Detonator, plunger",
    book: "Deadlands",
    weight: 10,
    costCents: 1000,
  },
  {
    id: "detonation-wire-per-50",
    name: "Detonation wire (per 50\u2019)",
    book: "Deadlands",
    weight: 1,
    costCents: 250,
  },
  {
    id: "derby",
    name: "Derby",
    book: "Deadlands",
    weight: 0,
    costCents: 150,
  },
  {
    id: "dehydrated-air-tablet",
    name: "Dehydrated air tablet",
    book: "Deadlands",
    weight: 0,
    costCents: 3000,
  },
  {
    id: "coffee-per-lb",
    name: "Coffee (per lb)",
    book: "Deadlands",
    weight: 1,
    costCents: 25,
  },
  {
    id: "cigar",
    name: "Cigar",
    book: "Deadlands",
    weight: 0,
    costCents: 5,
  },
  {
    id: "canteen",
    name: "Canteen",
    book: "Deadlands",
    weight: 5,
    costCents: 100,
  },
  {
    id: "camera",
    name: "Camera",
    book: "Deadlands",
    weight: 5,
    costCents: 300,
  },
  {
    id: "boots",
    name: "Boots",
    book: "Deadlands",
    weight: 4,
    costCents: 800,
  },
  {
    id: "bonnet",
    name: "Bonnet",
    book: "Deadlands",
    weight: 0,
    costCents: 200,
  },
  {
    id: "blasting-cap",
    name: "Blasting Cap",
    book: "Deadlands",
    weight: 0,
    costCents: 100,
  },
  {
    id: "bedroll",
    name: "Bedroll",
    book: "Deadlands",
    weight: 10,
    costCents: 400,
  },
  {
    id: "barbed-wire-per-yard",
    name: "Barbed wire (per yard)",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "bacon-per-lb",
    name: "Bacon (per lb)",
    book: "Deadlands",
    weight: 1,
    costCents: 15,
  },
  {
    id: "backpack",
    name: "Backpack",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "ax-wood",
    name: "Ax, wood",
    book: "Deadlands",
    weight: 5,
    costCents: 200,
  },
  {
    id: "arrow",
    name: "Arrow",
    book: "Deadlands",
    weight: 0.2,
    costCents: 10,
  },
  {
    id: "adrenal-booster",
    name: "Adrenal booster",
    book: "Deadlands",
    weight: 0,
    costCents: 20000,
  },
];
const ARMOR_LOCATIONS = [
  { id: "head", label: "Head" },
  { id: "face", label: "Face" },
  { id: "torso", label: "Torso" },
  { id: "arms", label: "Arms" },
  { id: "legs", label: "Legs" },
  { id: "shield", label: "Shield / carried" },
];
const ARMOR_CATALOG = [
  {
    id: "native-shield-small",
    name: "Native Shield (Small)",
    book: "Deadlands",
    armor: 1,
    weight: 3,
    minStr: "d4",
    costCents: 200,
    location: "shield",
  },
  {
    id: "native-shield-medium",
    name: "Native Shield (Medium)",
    book: "Deadlands",
    armor: 2,
    weight: 5,
    minStr: "d4",
    costCents: 300,
    location: "shield",
  },
  {
    id: "native-armor",
    name: "Native Armor",
    book: "Deadlands",
    armor: 1,
    weight: 3,
    minStr: "d4",
    costCents: 200,
    location: "torso",
  },
  {
    id: "inventors-apron",
    name: "Inventor’s apron",
    book: "Deadlands",
    armor: 1,
    weight: 4,
    minStr: "d4",
    costCents: 4000,
    location: "torso",
  },
  {
    id: "chaps",
    name: "Chaps",
    book: "Deadlands",
    armor: 1,
    weight: 6,
    minStr: "d4",
    costCents: 400,
    location: "legs",
  },
  {
    id: "armored-vest-corset-light",
    name: "Armored vest/corset (light)",
    book: "Deadlands",
    armor: 1,
    weight: 5,
    minStr: "d4",
    costCents: 10000,
    location: "torso",
  },
  {
    id: "armored-vest-corset-heavy",
    name: "Armored vest/corset (heavy)",
    book: "Deadlands",
    armor: 2,
    weight: 20,
    minStr: "d6",
    costCents: 50000,
    location: "torso",
  },
  {
    id: "armored-hat-light",
    name: "Armored hat (light)",
    book: "Deadlands",
    armor: 1,
    weight: 2,
    minStr: "d4",
    costCents: 4000,
    location: "head",
  },
  {
    id: "armored-hat-heavy",
    name: "Armored hat (heavy)",
    book: "Deadlands",
    armor: 2,
    weight: 4,
    minStr: "d4",
    costCents: 8000,
    location: "head",
  },
  {
    id: "armored-duster-light",
    name: "Armored duster (light)",
    book: "Deadlands",
    armor: 1,
    weight: 10,
    minStr: "d6",
    costCents: 20000,
    location: "torso",
  },
  {
    id: "armored-duster-heavy",
    name: "Armored duster (heavy)",
    book: "Deadlands",
    armor: 2,
    weight: 20,
    minStr: "d8",
    costCents: 40000,
    location: "torso",
  },
];
const WEAPON_CATALOG = [
  {
    "id": "ww-brass-knuckles",
    "name": "Brass Knuckles",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d4",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d4",
    "weight": 1,
    "weightText": "1",
    "costCents": 100,
    "costText": "$1",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Does not count as a weapon for Unarmed Defender."
  },
  {
    "id": "ww-bayonet",
    "name": "Bayonet",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d4",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d4",
    "weight": 1,
    "weightText": "1",
    "costCents": 500,
    "costText": "$5",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Str+d6 and Parry +1 if attached to a rifle; Reach 1; two hands."
  },
  {
    "id": "ww-club",
    "name": "Club",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d4",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d4",
    "weight": 1,
    "weightText": "1",
    "costCents": 100,
    "costText": "$1",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-club-war",
    "name": "Club, War",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d6",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d6",
    "weight": 3,
    "weightText": "3",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-club-war-bladed",
    "name": "Club, War (Bladed)",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d8",
    "range": "",
    "ap": "2",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d8",
    "weight": 6,
    "weightText": "6",
    "costCents": 800,
    "costText": "$8",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Parry -1; two hands."
  },
  {
    "id": "ww-knife",
    "name": "Knife",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d4",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d4",
    "weight": 1,
    "weightText": "1",
    "costCents": 200,
    "costText": "$2",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-knife-bowie",
    "name": "Knife, Bowie",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d4+1",
    "range": "",
    "ap": "1",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 400,
    "costText": "$4",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-lance-plains-indian",
    "name": "Lance (Plains Indian)",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d6",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d6",
    "weight": 4,
    "weightText": "4",
    "costCents": 2000,
    "costText": "$20",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Reach 2; mounted combat only."
  },
  {
    "id": "ww-lariat",
    "name": "Lariat",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d4",
    "weight": 3,
    "weightText": "3",
    "costCents": 400,
    "costText": "$4",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Parry -1; Reach 2. Used to initiate a Test with Fighting. Target is Entangled on success, Bound on a raise."
  },
  {
    "id": "ww-saber",
    "name": "Saber",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d6",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d6",
    "weight": 4,
    "weightText": "4",
    "costCents": 1500,
    "costText": "$15",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Typically used by cavalry."
  },
  {
    "id": "ww-spear",
    "name": "Spear",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d6",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d6",
    "weight": 5,
    "weightText": "5",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Parry +1; Reach 1; two hands."
  },
  {
    "id": "ww-tomahawk",
    "name": "Tomahawk",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d6",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d6",
    "weight": 4,
    "weightText": "4",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-whip",
    "name": "Whip",
    "book": "Deadlands: The Weird West",
    "category": "Melee Weapons",
    "damage": "Str+d4",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 1000,
    "costText": "$10",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Parry -1; Reach 2. With a raise on the attack roll, the victim is Entangled instead of taking bonus d6 damage."
  },
  {
    "id": "ww-gatling-pistol-36",
    "name": "Gatling Pistol (.36)",
    "book": "Deadlands: The Weird West",
    "category": "Personal Gatling Weapons",
    "damage": "2d6",
    "range": "12/24/48",
    "ap": "1",
    "rof": "3",
    "shotsMax": 30,
    "shotsText": "30",
    "minStr": "d4",
    "weight": 5,
    "weightText": "5",
    "costCents": 40000,
    "costText": "$400",
    "ammoType": "gatling-pistol-drum",
    "caliber": ".36",
    "modeOf": "",
    "notes": "Gatling weapons cannot fire single shots and must fire their full Rate of Fire. On a Critical Failure, the weapon jams and needs a Repair roll as an action. Pistol drums can be replaced in one action."
  },
  {
    "id": "ww-gatling-carbine-45",
    "name": "Gatling Carbine (.45)",
    "book": "Deadlands: The Weird West",
    "category": "Personal Gatling Weapons",
    "damage": "2d8",
    "range": "20/40/80",
    "ap": "2",
    "rof": "2",
    "shotsMax": 30,
    "shotsText": "30",
    "minStr": "d6",
    "weight": 12,
    "weightText": "12",
    "costCents": 75000,
    "costText": "$750",
    "ammoType": "gatling-rifle-carbine-drum",
    "caliber": ".45",
    "modeOf": "",
    "notes": "Gatling weapons cannot fire single shots and must fire their full Rate of Fire. On a Critical Failure, the weapon jams and needs a Repair roll as an action. Carbine drums can be replaced in one action."
  },
  {
    "id": "ww-gatling-rifle-45",
    "name": "Gatling Rifle (.45)",
    "book": "Deadlands: The Weird West",
    "category": "Personal Gatling Weapons",
    "damage": "2d8",
    "range": "24/48/96",
    "ap": "2",
    "rof": "2",
    "shotsMax": 30,
    "shotsText": "30",
    "minStr": "d8",
    "weight": 17,
    "weightText": "17",
    "costCents": 100000,
    "costText": "$1,000",
    "ammoType": "gatling-rifle-carbine-drum",
    "caliber": ".45",
    "modeOf": "",
    "notes": "Gatling weapons cannot fire single shots and must fire their full Rate of Fire. On a Critical Failure, the weapon jams and needs a Repair roll as an action. Rifle drums can be replaced in one action."
  },
  {
    "id": "ww-gatling-shotgun",
    "name": "Gatling Shotgun",
    "book": "Deadlands: The Weird West",
    "category": "Personal Gatling Weapons",
    "damage": "1-3d6",
    "range": "12/24/48",
    "ap": "",
    "rof": "2",
    "shotsMax": 15,
    "shotsText": "15",
    "minStr": "d8",
    "weight": 15,
    "weightText": "15",
    "costCents": 100000,
    "costText": "$1,000",
    "ammoType": "gatling-shotgun-drum",
    "caliber": "12-ga",
    "modeOf": "",
    "notes": "Gatling weapons cannot fire single shots and must fire their full Rate of Fire. On a Critical Failure, the weapon jams and needs a Repair roll as an action. Shotgun drums can be replaced in one action. Shotgun damage varies by range band."
  },
  {
    "id": "ww-gatling-gun-45",
    "name": "Gatling Gun (.45)",
    "book": "Deadlands: The Weird West",
    "category": "Gatling Guns",
    "damage": "2d8",
    "range": "24/48/96",
    "ap": "2",
    "rof": "3",
    "shotsMax": 100,
    "shotsText": "100",
    "minStr": "d6",
    "weight": 40,
    "weightText": "40",
    "costCents": 150000,
    "costText": "$1,500",
    "ammoType": "gatling-gun-45",
    "caliber": ".45",
    "modeOf": "",
    "notes": "Mounted on carriage or pintle mount, negating Recoil but possibly restricting firing arc. Early models use a 20-round stick; later models use a 100-round belt. Loading a stick takes one action. Loading a belt takes two actions. Gatling weapons cannot fire single shots and must fire their full Rate of Fire. On a Critical Failure, the weapon jams and needs a Repair roll as an action."
  },
  {
    "id": "ww-derringer-41",
    "name": "Derringer (.41)",
    "book": "Deadlands: The Weird West",
    "category": "Derringers & Pepperboxes",
    "damage": "2d4",
    "range": "3/6/12",
    "ap": "",
    "rof": "1",
    "shotsMax": 2,
    "shotsText": "2",
    "minStr": "d4",
    "weight": 1,
    "weightText": "1",
    "costCents": 500,
    "costText": "$5",
    "ammoType": "pistol-large",
    "caliber": ".41",
    "modeOf": "",
    "notes": "-2 to be Noticed if hidden."
  },
  {
    "id": "ww-english-1840-model-36",
    "name": "English 1840 Model (.36)",
    "book": "Deadlands: The Weird West",
    "category": "Derringers & Pepperboxes",
    "damage": "2d6-1",
    "range": "5/10/20",
    "ap": "1",
    "rof": "1",
    "shotsMax": 8,
    "shotsText": "8",
    "minStr": "d4",
    "weight": 1,
    "weightText": "1",
    "costCents": 500,
    "costText": "$5",
    "ammoType": "pistol-small",
    "caliber": ".36",
    "modeOf": "",
    "notes": "Reload 3; black powder weapon."
  },
  {
    "id": "ww-rupertus-pepperbox-22",
    "name": "Rupertus Pepperbox (.22)",
    "book": "Deadlands: The Weird West",
    "category": "Derringers & Pepperboxes",
    "damage": "2d4",
    "range": "5/10/20",
    "ap": "",
    "rof": "1",
    "shotsMax": 8,
    "shotsText": "8",
    "minStr": "d6",
    "weight": 1,
    "weightText": "1",
    "costCents": 600,
    "costText": "$6",
    "ammoType": "pistol-small",
    "caliber": ".22",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-wesson-dagger-pistol-41",
    "name": "Wesson Dagger-Pistol (.41)",
    "book": "Deadlands: The Weird West",
    "category": "Derringers & Pepperboxes",
    "damage": "2d4",
    "range": "5/10/20",
    "ap": "",
    "rof": "1",
    "shotsMax": 2,
    "shotsText": "2",
    "minStr": "d6",
    "weight": 1,
    "weightText": "1",
    "costCents": 600,
    "costText": "$6",
    "ammoType": "pistol-large",
    "caliber": ".41",
    "modeOf": "",
    "notes": "A knife blade dealing Str+d4 damage juts out from between the barrels."
  },
  {
    "id": "ww-colt-army-44",
    "name": "Colt Army (.44)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Single-Action",
    "damage": "2d6+1",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 1200,
    "costText": "$12",
    "ammoType": "pistol-large",
    "caliber": ".44",
    "modeOf": "",
    "notes": "Older versions are cap and ball weapons with Reload 3 and cost $10."
  },
  {
    "id": "ww-colt-buntline-special-45",
    "name": "Colt Buntline Special (.45)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Single-Action",
    "damage": "2d6+1",
    "range": "15/30/60",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d6",
    "weight": 3,
    "weightText": "3",
    "costCents": 50000,
    "costText": "$500",
    "ammoType": "pistol-large",
    "caliber": ".45",
    "modeOf": "",
    "notes": "16-inch barrel and detachable shoulder stock. Must be ordered direct from Colt. Does not benefit from quick-draw holsters."
  },
  {
    "id": "ww-colt-dragoon-44",
    "name": "Colt Dragoon (.44)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Single-Action",
    "damage": "2d6+1",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 4,
    "weightText": "4",
    "costCents": 1100,
    "costText": "$11",
    "ammoType": "pistol-large",
    "caliber": ".44",
    "modeOf": "",
    "notes": "Reload 3; black powder weapon."
  },
  {
    "id": "ww-colt-navy-36",
    "name": "Colt Navy (.36)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Single-Action",
    "damage": "2d6",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 3,
    "weightText": "3",
    "costCents": 1000,
    "costText": "$10",
    "ammoType": "pistol-small",
    "caliber": ".36",
    "modeOf": "",
    "notes": "Older versions are cap and ball weapons with Reload 3 and cost $8."
  },
  {
    "id": "ww-colt-peacemaker-45",
    "name": "Colt Peacemaker (.45)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Single-Action",
    "damage": "2d6+1",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 4,
    "weightText": "4",
    "costCents": 1500,
    "costText": "$15",
    "ammoType": "pistol-large",
    "caliber": ".45",
    "modeOf": "",
    "notes": "Also known as the Colt Single-Action Army."
  },
  {
    "id": "ww-lemat-revolver-40",
    "name": "LeMat Revolver (.40)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Single-Action",
    "damage": "2d6",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 9,
    "shotsText": "9",
    "minStr": "d6",
    "weight": 4,
    "weightText": "4",
    "costCents": 2500,
    "costText": "$25",
    "ammoType": "pistol-large",
    "caliber": ".40",
    "modeOf": "",
    "notes": "Includes a 20-gauge shotgun barrel mounted under the pistol. Switching between revolver and shotgun mode is a free action."
  },
  {
    "id": "ww-lemat-revolver-shotgun-barrel-20-ga",
    "name": "LeMat Revolver Shotgun Barrel (20-ga)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Single-Action",
    "damage": "1-3d6",
    "range": "5/10/20",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 4,
    "weightText": "4",
    "costCents": 2500,
    "costText": "$25",
    "ammoType": "shotgun-20ga",
    "caliber": "20-ga",
    "modeOf": "LeMat Revolver (.40)",
    "notes": "Alternate mode of the LeMat Revolver. Switching between revolver and shotgun mode is a free action. Shotgun damage varies by range band."
  },
  {
    "id": "ww-colt-frontier-44-40",
    "name": "Colt Frontier (.44-40)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Double-Action",
    "damage": "2d6+1",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 1500,
    "costText": "$15",
    "ammoType": "44-40",
    "caliber": ".44-40",
    "modeOf": "",
    "notes": "Also known as the Double-Action Army. Ammunition may be shared with the Winchester '73."
  },
  {
    "id": "ww-colt-lightning-38",
    "name": "Colt Lightning (.38)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Double-Action",
    "damage": "2d6",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 1300,
    "costText": "$13",
    "ammoType": "pistol-small",
    "caliber": ".38",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-colt-rainmaker-32",
    "name": "Colt Rainmaker (.32)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Double-Action",
    "damage": "2d6",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 800,
    "costText": "$8",
    "ammoType": "pistol-small",
    "caliber": ".32",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-colt-thunderer-41",
    "name": "Colt Thunderer (.41)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Double-Action",
    "damage": "2d6",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 1400,
    "costText": "$14",
    "ammoType": "pistol-large",
    "caliber": ".41",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-starr-revolver-44",
    "name": "Starr Revolver (.44)",
    "book": "Deadlands: The Weird West",
    "category": "Revolvers, Double-Action",
    "damage": "2d6+1",
    "range": "12/24/48",
    "ap": "1",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 900,
    "costText": "$9",
    "ammoType": "pistol-large",
    "caliber": ".44",
    "modeOf": "",
    "notes": "Older versions are cap and ball weapons with Reload 3 and cost $7."
  },
  {
    "id": "ww-sharps-55-57",
    "name": "Sharps '55 (.57)",
    "book": "Deadlands: The Weird West",
    "category": "Carbines",
    "damage": "2d8",
    "range": "20/40/80",
    "ap": "2",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 8,
    "weightText": "8",
    "costCents": 1800,
    "costText": "$18",
    "ammoType": "rifle-large",
    "caliber": ".57",
    "modeOf": "",
    "notes": "Reload 3; black powder weapon."
  },
  {
    "id": "ww-spencer-56",
    "name": "Spencer (.56)",
    "book": "Deadlands: The Weird West",
    "category": "Carbines",
    "damage": "2d8",
    "range": "20/40/80",
    "ap": "2",
    "rof": "1",
    "shotsMax": 7,
    "shotsText": "7",
    "minStr": "d4",
    "weight": 8,
    "weightText": "8",
    "costCents": 1500,
    "costText": "$15",
    "ammoType": "rifle-large",
    "caliber": ".56",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-lemat-carbine-42",
    "name": "LeMat Carbine (.42)",
    "book": "Deadlands: The Weird West",
    "category": "Carbines",
    "damage": "2d8",
    "range": "20/40/80",
    "ap": "1",
    "rof": "1",
    "shotsMax": 9,
    "shotsText": "9",
    "minStr": "d6",
    "weight": 9,
    "weightText": "9",
    "costCents": 3500,
    "costText": "$35",
    "ammoType": "rifle-small",
    "caliber": ".42",
    "modeOf": "",
    "notes": "Includes a 20-gauge shotgun barrel mounted under the rifle. Switching between carbine and shotgun mode is a free action. Carbine and shotgun are cap and ball weapons with Reload 3."
  },
  {
    "id": "ww-lemat-carbine-shotgun-barrel-20-ga",
    "name": "LeMat Carbine Shotgun Barrel (20-ga)",
    "book": "Deadlands: The Weird West",
    "category": "Carbines",
    "damage": "1-3d6",
    "range": "12/24/48",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 9,
    "weightText": "9",
    "costCents": 3500,
    "costText": "$35",
    "ammoType": "shotgun-20ga",
    "caliber": "20-ga",
    "modeOf": "LeMat Carbine (.42)",
    "notes": "Alternate mode of the LeMat Carbine. Switching between carbine and shotgun mode is a free action. Carbine and shotgun are cap and ball weapons with Reload 3. Shotgun damage varies by range band."
  },
  {
    "id": "ww-ballard-72-56",
    "name": "Ballard '72 (.56)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d8",
    "range": "24/48/96",
    "ap": "2",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 11,
    "weightText": "11",
    "costCents": 2400,
    "costText": "$24",
    "ammoType": "rifle-large",
    "caliber": ".56",
    "modeOf": "",
    "notes": "Reload 3; black powder weapon."
  },
  {
    "id": "ww-bullard-express-50",
    "name": "Bullard Express (.50)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d10",
    "range": "24/48/96",
    "ap": "2",
    "rof": "1",
    "shotsMax": 11,
    "shotsText": "11",
    "minStr": "d8",
    "weight": 11,
    "weightText": "11",
    "costCents": 3000,
    "costText": "$30",
    "ammoType": "rifle-large",
    "caliber": ".50",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-colt-paterson-model-36-69",
    "name": "Colt-Paterson Model '36 (.69)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d10",
    "range": "24/48/96",
    "ap": "2",
    "rof": "1",
    "shotsMax": 7,
    "shotsText": "7",
    "minStr": "d8",
    "weight": 12,
    "weightText": "12",
    "costCents": 2500,
    "costText": "$25",
    "ammoType": "rifle-large",
    "caliber": ".69",
    "modeOf": "",
    "notes": "Reload 3; black powder weapon."
  },
  {
    "id": "ww-enfield-musket-58",
    "name": "Enfield Musket (.58)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d8",
    "range": "12/24/48",
    "ap": "2",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 9,
    "weightText": "9",
    "costCents": 2500,
    "costText": "$25",
    "ammoType": "rifle-large",
    "caliber": ".58",
    "modeOf": "",
    "notes": "Reload 3; black powder weapon."
  },
  {
    "id": "ww-evans-old-model-sporter-44",
    "name": "Evans Old Model Sporter (.44)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d8",
    "range": "24/48/96",
    "ap": "2",
    "rof": "1",
    "shotsMax": 34,
    "shotsText": "34",
    "minStr": "d6",
    "weight": 12,
    "weightText": "12",
    "costCents": 3000,
    "costText": "$30",
    "ammoType": "rifle-small",
    "caliber": ".44",
    "modeOf": "",
    "notes": "Uses special .44-caliber ammunition made only by the manufacturer. Delivery takes about three weeks if ordered directly."
  },
  {
    "id": "ww-sawed-off-winchester-44-40",
    "name": "Sawed-Off Winchester (.44-40)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d8-1",
    "range": "12/24/48",
    "ap": "2",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d4",
    "weight": 4,
    "weightText": "4",
    "costCents": 2500,
    "costText": "$25",
    "ammoType": "44-40",
    "caliber": ".44-40",
    "modeOf": "",
    "notes": "Commonly known as a mare's leg. About as easy to conceal as a pistol."
  },
  {
    "id": "ww-sharps-big-50-50",
    "name": "Sharp's Big 50 (.50)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d10",
    "range": "30/60/120",
    "ap": "2",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d8",
    "weight": 11,
    "weightText": "11",
    "costCents": 5000,
    "costText": "$50",
    "ammoType": "rifle-large",
    "caliber": ".50",
    "modeOf": "",
    "notes": "Snapfire; cap and ball firearm; Reload 3."
  },
  {
    "id": "ww-springfield-rifled-musket-58",
    "name": "Springfield Rifled Musket (.58)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d8",
    "range": "15/30/60",
    "ap": "",
    "rof": "1",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d6",
    "weight": 11,
    "weightText": "11",
    "costCents": 800,
    "costText": "$8",
    "ammoType": "rifle-large",
    "caliber": ".58",
    "modeOf": "",
    "notes": "Shots are listed as blank in the source table. Reload 3; black powder weapon."
  },
  {
    "id": "ww-winchester-73-44-40",
    "name": "Winchester '73 (.44-40)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d8-1",
    "range": "24/48/96",
    "ap": "2",
    "rof": "1",
    "shotsMax": 15,
    "shotsText": "15",
    "minStr": "d6",
    "weight": 10,
    "weightText": "10",
    "costCents": 2500,
    "costText": "$25",
    "ammoType": "44-40",
    "caliber": ".44-40",
    "modeOf": "",
    "notes": "Ammunition may be shared with Colt Frontier (.44-40)."
  },
  {
    "id": "ww-winchester-76-45",
    "name": "Winchester '76 (.45)",
    "book": "Deadlands: The Weird West",
    "category": "Rifles",
    "damage": "2d8",
    "range": "24/48/96",
    "ap": "2",
    "rof": "1",
    "shotsMax": 15,
    "shotsText": "15",
    "minStr": "d4",
    "weight": 7,
    "weightText": "7",
    "costCents": 4000,
    "costText": "$40",
    "ammoType": "rifle-large",
    "caliber": ".45",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-colt-revolving-shotgun",
    "name": "Colt Revolving Shotgun",
    "book": "Deadlands: The Weird West",
    "category": "Shotguns",
    "damage": "1-3d6",
    "range": "12/24/48",
    "ap": "",
    "rof": "1",
    "shotsMax": 5,
    "shotsText": "5",
    "minStr": "d6",
    "weight": 10,
    "weightText": "10",
    "costCents": 4500,
    "costText": "$45",
    "ammoType": "shotgun-shells",
    "caliber": "12-ga",
    "modeOf": "",
    "notes": "Shotguns get +2 Shooting. Damage is 3d6 at Short Range, 2d6 at Medium Range, and 1d6 at Long Range. Cap and ball weapon; Reload 3."
  },
  {
    "id": "ww-double-barrel-shotgun",
    "name": "Double-Barrel Shotgun",
    "book": "Deadlands: The Weird West",
    "category": "Shotguns",
    "damage": "1-3d6",
    "range": "12/24/48",
    "ap": "",
    "rof": "1",
    "shotsMax": 2,
    "shotsText": "2",
    "minStr": "d6",
    "weight": 11,
    "weightText": "11",
    "costCents": 3500,
    "costText": "$35",
    "ammoType": "shotgun-shells",
    "caliber": "12-ga",
    "modeOf": "",
    "notes": "Shotguns get +2 Shooting. Damage is 3d6 at Short Range, 2d6 at Medium Range, and 1d6 at Long Range. If both barrels are fired at the same target, roll damage once and add +4."
  },
  {
    "id": "ww-sawed-off-double-barrel-shotgun",
    "name": "Sawed-Off Double-Barrel Shotgun",
    "book": "Deadlands: The Weird West",
    "category": "Shotguns",
    "damage": "1-3d6",
    "range": "5/10/20",
    "ap": "",
    "rof": "1",
    "shotsMax": 2,
    "shotsText": "2",
    "minStr": "d4",
    "weight": 6,
    "weightText": "6",
    "costCents": 3500,
    "costText": "$35",
    "ammoType": "shotgun-shells",
    "caliber": "12-ga",
    "modeOf": "",
    "notes": "Shotguns get +2 Shooting. Damage is 3d6 at Short Range, 2d6 at Medium Range, and 1d6 at Long Range. As double-barrel. May be fired in melee using the Savage Worlds ranged weapons in melee rule."
  },
  {
    "id": "ww-single-barrel-shotgun",
    "name": "Single-Barrel Shotgun",
    "book": "Deadlands: The Weird West",
    "category": "Shotguns",
    "damage": "1-3d6",
    "range": "12/24/48",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d4",
    "weight": 6,
    "weightText": "6",
    "costCents": 2500,
    "costText": "$25",
    "ammoType": "shotgun-shells",
    "caliber": "12-ga",
    "modeOf": "",
    "notes": "Shotguns get +2 Shooting. Damage is 3d6 at Short Range, 2d6 at Medium Range, and 1d6 at Long Range."
  },
  {
    "id": "ww-winchester-lever-action-shotgun",
    "name": "Winchester Lever-Action Shotgun",
    "book": "Deadlands: The Weird West",
    "category": "Shotguns",
    "damage": "1-3d6",
    "range": "12/24/48",
    "ap": "",
    "rof": "1",
    "shotsMax": 4,
    "shotsText": "4",
    "minStr": "d6",
    "weight": 8,
    "weightText": "8",
    "costCents": 3500,
    "costText": "$35",
    "ammoType": "shotgun-shells",
    "caliber": "12-ga",
    "modeOf": "",
    "notes": "Shotguns get +2 Shooting. Damage is 3d6 at Short Range, 2d6 at Medium Range, and 1d6 at Long Range."
  },
  {
    "id": "ww-bola",
    "name": "Bola",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "Str+1",
    "range": "4/8/16",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d4",
    "weight": 0.5,
    "weightText": "0.5",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "thrown",
    "caliber": "",
    "modeOf": "",
    "notes": "With a raise on the attack roll, the victim is Entangled instead of taking bonus d6 damage."
  },
  {
    "id": "ww-bow",
    "name": "Bow",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "2d6",
    "range": "12/24/48",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 2,
    "weightText": "2",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "arrow",
    "caliber": "",
    "modeOf": "",
    "notes": ""
  },
  {
    "id": "ww-knife-thrown",
    "name": "Knife, Thrown",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "Str+d4",
    "range": "3/6/12",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d4",
    "weight": 1,
    "weightText": "1",
    "costCents": 200,
    "costText": "$2",
    "ammoType": "thrown",
    "caliber": "",
    "modeOf": "",
    "notes": "Thrown profile for Knife."
  },
  {
    "id": "ww-knife-bowie-thrown",
    "name": "Knife, Bowie, Thrown",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "Str+d4+1",
    "range": "2/4/8",
    "ap": "1",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d4",
    "weight": 2,
    "weightText": "2",
    "costCents": 400,
    "costText": "$4",
    "ammoType": "thrown",
    "caliber": "",
    "modeOf": "",
    "notes": "Thrown profile for Knife, Bowie."
  },
  {
    "id": "ww-lance-plains-indian-thrown",
    "name": "Lance (Plains Indian), Thrown",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "Str+d6",
    "range": "2/4/8",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 4,
    "weightText": "4",
    "costCents": 2000,
    "costText": "$20",
    "ammoType": "thrown",
    "caliber": "",
    "modeOf": "",
    "notes": "Reach 2; mounted combat only; may only be thrown from horseback."
  },
  {
    "id": "ww-spear-thrown",
    "name": "Spear, Thrown",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "Str+d6",
    "range": "3/6/12",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 5,
    "weightText": "5",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "thrown",
    "caliber": "",
    "modeOf": "",
    "notes": "Thrown profile for Spear."
  },
  {
    "id": "ww-tomahawk-thrown",
    "name": "Tomahawk, Thrown",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "Str+d6",
    "range": "3/6/12",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 3,
    "weightText": "3",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "thrown",
    "caliber": "",
    "modeOf": "",
    "notes": "Thrown profile for Tomahawk."
  },
  {
    "id": "ww-war-club-thrown",
    "name": "War Club, Thrown",
    "book": "Deadlands: The Weird West",
    "category": "Other Ranged Weapons",
    "damage": "Str+d6",
    "range": "3/6/12",
    "ap": "",
    "rof": "1",
    "shotsMax": 1,
    "shotsText": "1",
    "minStr": "d6",
    "weight": 3,
    "weightText": "3",
    "costCents": 300,
    "costText": "$3",
    "ammoType": "thrown",
    "caliber": "",
    "modeOf": "",
    "notes": "Thrown profile for War Club."
  },
  {
    "id": "ww-dynamite-nitro-1-2-sticks-or-pints",
    "name": "Dynamite/Nitro, 1-2 sticks or pints",
    "book": "Deadlands: The Weird West",
    "category": "Dynamite & Nitroglycerine",
    "damage": "2d6",
    "range": "4/8/16",
    "ap": "",
    "rof": "1",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "",
    "weight": null,
    "weightText": "0.5/1",
    "costCents": null,
    "costText": "$3 per stick or pint",
    "ammoType": "explosive",
    "caliber": "",
    "modeOf": "",
    "notes": "Dynamite and nitroglycerine are Heavy Weapons. Throwing uses Athletics; setting uses Repair. Dynamite costs $3 per stick. Each pint of nitroglycerine acts as one stick of dynamite. Medium Blast Template; +2 damage for 2 sticks or pints."
  },
  {
    "id": "ww-dynamite-nitro-3-4-sticks-or-pints",
    "name": "Dynamite/Nitro, 3-4 sticks or pints",
    "book": "Deadlands: The Weird West",
    "category": "Dynamite & Nitroglycerine",
    "damage": "3d6",
    "range": "3/6/12",
    "ap": "",
    "rof": "1",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "",
    "weight": null,
    "weightText": "1.5/2",
    "costCents": null,
    "costText": "$3 per stick or pint",
    "ammoType": "explosive",
    "caliber": "",
    "modeOf": "",
    "notes": "Dynamite and nitroglycerine are Heavy Weapons. Throwing uses Athletics; setting uses Repair. Dynamite costs $3 per stick. Each pint of nitroglycerine acts as one stick of dynamite. Large Blast Template; +2 damage for 4 sticks or pints."
  },
  {
    "id": "ww-dynamite-nitro-5-6-sticks-or-pints",
    "name": "Dynamite/Nitro, 5-6 sticks or pints",
    "book": "Deadlands: The Weird West",
    "category": "Dynamite & Nitroglycerine",
    "damage": "4d6",
    "range": "2/4/8",
    "ap": "",
    "rof": "1",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "",
    "weight": null,
    "weightText": "2.5/3",
    "costCents": null,
    "costText": "$3 per stick or pint",
    "ammoType": "explosive",
    "caliber": "",
    "modeOf": "",
    "notes": "Dynamite and nitroglycerine are Heavy Weapons. Throwing uses Athletics; setting uses Repair. Dynamite costs $3 per stick. Each pint of nitroglycerine acts as one stick of dynamite. 6-inch radius; +2 damage for 6 sticks or pints."
  },
  {
    "id": "ww-dynamite-nitro-each-additional-stick-or-pint",
    "name": "Dynamite/Nitro, each additional stick or pint",
    "book": "Deadlands: The Weird West",
    "category": "Dynamite & Nitroglycerine",
    "damage": "+2",
    "range": "",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "",
    "weight": null,
    "weightText": "+0.5/1",
    "costCents": null,
    "costText": "$3 per stick or pint",
    "ammoType": "explosive",
    "caliber": "",
    "modeOf": "",
    "notes": "Dynamite and nitroglycerine are Heavy Weapons. Throwing uses Athletics; setting uses Repair. Dynamite costs $3 per stick. Each pint of nitroglycerine acts as one stick of dynamite. Add +0.5 inch radius per additional stick or pint."
  },
  {
    "id": "ww-flamethrower",
    "name": "Flamethrower",
    "book": "Deadlands: The Weird West",
    "category": "Infernal Device Weapons",
    "damage": "3d6",
    "range": "Cone Template",
    "ap": "",
    "rof": "1",
    "shotsMax": 6,
    "shotsText": "6",
    "minStr": "d6",
    "weight": 15,
    "weightText": "15",
    "costCents": 70000,
    "costText": "$700",
    "ammoType": "ghost-rock-fuel",
    "caliber": "",
    "modeOf": "",
    "notes": "Heavy Weapon. Attack may be Evaded. Flammable targets may catch fire. Uses a one-pound chunk of ghost rock as fuel."
  },
  {
    "id": "ww-steam-saw",
    "name": "Steam Saw",
    "book": "Deadlands: The Weird West",
    "category": "Infernal Device Weapons",
    "damage": "2d6+4",
    "range": "Melee",
    "ap": "",
    "rof": "",
    "shotsMax": null,
    "shotsText": "",
    "minStr": "d8",
    "weight": 20,
    "weightText": "20",
    "costCents": 80000,
    "costText": "$800",
    "ammoType": "",
    "caliber": "",
    "modeOf": "",
    "notes": "Steam-powered saw. On a Critical Failure Malfunction, it hits the user instead. Boiler is usually ground-mounted via 20-foot hose; worn boiler weighs 30 pounds and requires ghost steel backpack protection."
  },
  {
    "id": "ww-steam-gatling",
    "name": "Steam Gatling",
    "book": "Deadlands: The Weird West",
    "category": "Infernal Device Weapons",
    "damage": "2d8",
    "range": "24/48/96",
    "ap": "2",
    "rof": "4",
    "shotsMax": 100,
    "shotsText": "100",
    "minStr": "d6",
    "weight": 50,
    "weightText": "50",
    "costCents": 300000,
    "costText": "$3,000",
    "ammoType": "gatling-gun-45",
    "caliber": ".45",
    "modeOf": "",
    "notes": "Standard Gatling gun attached to a high-pressure steam boiler. Gatlings must fire their full Rate of Fire. On a Critical Failure, it jams and needs a Repair roll as an action."
  }
];
const VEHICLE_CATALOG = [
  {
    id: "whirligig-personal",
    name: "Whirligig (Personal)",
    book: "Deadlands",
    costCents: 100000,
  },
  { id: "wagon", name: "Wagon", book: "Deadlands", costCents: 20000 },
  {
    id: "velocipede",
    name: "Velocipede",
    book: "Deadlands",
    costCents: 100000,
  },
  { id: "train-car", name: "Train Car", book: "Deadlands", costCents: 800000 },
  {
    id: "super-gyro",
    name: "Super Gyro",
    book: "Deadlands",
    costCents: 400000,
  },
  {
    id: "submersible-boat",
    name: "Submersible boat",
    book: "Deadlands",
    costCents: 2000000,
  },
  {
    id: "steam-wagon",
    name: "Steam Wagon",
    book: "Deadlands",
    costCents: 150000,
  },
  { id: "steam-cart", name: "Steam Cart", book: "Deadlands", costCents: 80000 },
  { id: "stagecoach", name: "Stagecoach", book: "Deadlands", costCents: 30000 },
  {
    id: "rocket-pack",
    name: "Rocket Pack",
    book: "Deadlands",
    costCents: 210000,
  },
  {
    id: "rail-runner",
    name: "Rail Runner",
    book: "Deadlands",
    costCents: 250000,
  },
  {
    id: "powered-ornithopter",
    name: "Powered Ornithopter",
    book: "Deadlands",
    costCents: 300000,
  },
  {
    id: "paddlewheeler-large",
    name: "Paddlewheeler, Large",
    book: "Deadlands",
    costCents: 5000000,
  },
  {
    id: "paddlewheel-small",
    name: "Paddlewheel, Small",
    book: "Deadlands",
    costCents: 2000000,
  },
  {
    id: "maze-runner",
    name: "Maze Runner",
    book: "Deadlands",
    costCents: 1500000,
  },
  {
    id: "locomotive",
    name: "Locomotive",
    book: "Deadlands",
    costCents: 1500000,
  },
  { id: "carriage", name: "Carriage", book: "Deadlands", costCents: 20000 },
  {
    id: "buckboard-buggy",
    name: "Buckboard/buggy",
    book: "Deadlands",
    costCents: 7500,
  },
  { id: "bateaux", name: "Bateaux", book: "Deadlands", costCents: 5000 },
  { id: "auto-gyro", name: "Auto-Gyro", book: "Deadlands", costCents: 150000 },
  {
    id: "air-carriage",
    name: "Air Carriage",
    book: "Deadlands",
    costCents: 500000,
  },
];
