const GEAR_CATALOG = [
  {
    id: "winter-coat",
    name: "Winter coat",
    book: "Deadlands",
    weight: 3,
    costCents: 1500,
  },
  {
    id: "watch-standard",
    name: "Watch, standard",
    book: "Deadlands",
    weight: 0.5,
    costCents: 250,
  },
  {
    id: "watch-gold",
    name: "Watch, gold",
    book: "Deadlands",
    weight: 0.5,
    costCents: 1000,
  },
  {
    id: "vocal-unction-elixir",
    name: "Vocal unction elixir",
    book: "Deadlands",
    weight: 0,
    costCents: 5000,
  },
  {
    id: "vapor-mask",
    name: "Vapor mask",
    book: "Deadlands",
    weight: 0.5,
    costCents: 10000,
  },
  {
    id: "trousers-skirt",
    name: "Trousers/skirt",
    book: "Deadlands",
    weight: 2,
    costCents: 200,
  },
  {
    id: "trail-rations-per-day",
    name: "Trail Rations (per day)",
    book: "Deadlands",
    weight: 3,
    costCents: 50,
  },
  {
    id: "tool-kit-weird-science",
    name: "Tool Kit (Weird Science)",
    book: "Deadlands",
    weight: 5,
    costCents: 5000,
  },
  {
    id: "tool-kit",
    name: "Tool kit",
    book: "Deadlands",
    weight: 5,
    costCents: 2500,
  },
  {
    id: "tobacco-smoking-pouch",
    name: "Tobacco, smoking (pouch)",
    book: "Deadlands",
    weight: 1,
    costCents: 50,
  },
  {
    id: "tobacco-chewing-tin",
    name: "Tobacco, chewing (tin)",
    book: "Deadlands",
    weight: 1,
    costCents: 50,
  },
  {
    id: "tactile-desensitizer",
    name: "Tactile desensitizer",
    book: "Deadlands",
    weight: 0,
    costCents: 3000,
  },
  {
    id: "suit-fancy-dress",
    name: "Suit/fancy dress",
    book: "Deadlands",
    weight: 6,
    costCents: 1500,
  },
  {
    id: "stetson",
    name: "Stetson",
    book: "Deadlands",
    weight: 0,
    costCents: 500,
  },
  {
    id: "spring-boots",
    name: "Spring Boots",
    book: "Deadlands",
    weight: 2,
    costCents: 40000,
  },
  {
    id: "speed-load-cylinder",
    name: "Speed-load cylinder",
    book: "Deadlands",
    weight: 0.25,
    costCents: 300,
  },
  {
    id: "spectacles",
    name: "Spectacles",
    book: "Deadlands",
    weight: 0,
    costCents: 500,
  },
  {
    id: "sombrero",
    name: "Sombrero",
    book: "Deadlands",
    weight: 0,
    costCents: 350,
  },
  {
    id: "silver-ore",
    name: "Silver ore",
    book: "Deadlands",
    weight: 1,
    costCents: 2400,
  },
  {
    id: "silk-stockings",
    name: "Silk Stockings",
    book: "Deadlands",
    weight: 0,
    costCents: 100,
  },
  {
    id: "shovel",
    name: "Shovel",
    book: "Deadlands",
    weight: 5,
    costCents: 150,
  },
  {
    id: "shotgun-thong",
    name: "Shotgun thong",
    book: "Deadlands",
    weight: 0,
    costCents: 25,
  },
  {
    id: "shotgun-shells",
    name: "Shotgun shells",
    book: "Deadlands",
    weight: 0.1,
    costCents: 10,
  },
  {
    id: "shot-w-powder",
    name: "Shot w/powder",
    book: "Deadlands",
    weight: 0.2,
    costCents: 5,
  },
  {
    id: "shoes",
    name: "Shoes",
    book: "Deadlands",
    weight: 1,
    costCents: 200,
  },
  {
    id: "shirt-blouse-work",
    name: "Shirt/blouse, work",
    book: "Deadlands",
    weight: 1,
    costCents: 100,
  },
  {
    id: "shirt-blouse-dress",
    name: "Shirt/blouse, dress",
    book: "Deadlands",
    weight: 1,
    costCents: 300,
  },
  {
    id: "scope",
    name: "Scope",
    book: "Deadlands",
    weight: 2,
    costCents: 3000,
  },
  {
    id: "samson-s-elixir",
    name: "Samson's elixir",
    book: "Deadlands",
    weight: 0,
    costCents: 6000,
  },
  {
    id: "saddlebags",
    name: "Saddlebags",
    book: "Deadlands",
    weight: 5,
    costCents: 500,
  },
  {
    id: "saddle",
    name: "Saddle",
    book: "Deadlands",
    weight: 30,
    costCents: 2500,
  },
  {
    id: "rope-10",
    name: 'Rope (10")',
    book: "Deadlands",
    weight: 8,
    costCents: 500,
  },
  {
    id: "rifle-boot",
    name: "Rifle Boot",
    book: "Deadlands",
    weight: 0.5,
    costCents: 300,
  },
  {
    id: "rifle-ammunition-small-38-44-caliber",
    name: "Rifle Ammunition (Small, .38-.44 caliber)",
    book: "Deadlands",
    weight: 0.12,
    costCents: 8,
  },
  {
    id: "rifle-ammunition-large-50-caliber",
    name: "Rifle Ammunition (Large, .50+ caliber)",
    book: "Deadlands",
    weight: 0.16,
    costCents: 10,
  },
  {
    id: "restoration-elixir",
    name: "Restoration elixir",
    book: "Deadlands",
    weight: 0,
    costCents: 10000,
  },
  {
    id: "refined-ghost-rock",
    name: "Refined Ghost Rock",
    book: "Deadlands",
    weight: 1,
    costCents: 15000,
  },
  {
    id: "rattler-detector",
    name: "Rattler detector",
    book: "Deadlands",
    weight: 5,
    costCents: 10000,
  },
  {
    id: "quick-draw-holster",
    name: "Quick-draw holster",
    book: "Deadlands",
    weight: 1,
    costCents: 1100,
  },
  {
    id: "powered-de-moler",
    name: "Powered De-Moler",
    book: "Deadlands",
    weight: 5,
    costCents: 12000,
  },
  {
    id: "playing-cards",
    name: "Playing cards",
    book: "Deadlands",
    weight: 0,
    costCents: 25,
  },
  {
    id: "pistol-ammunition-small-22-38-caliber",
    name: "Pistol Ammunition (Small, .22-.38 caliber)",
    book: "Deadlands",
    weight: 0.06,
    costCents: 4,
  },
  {
    id: "pistol-ammunition-large-40-50-caliber",
    name: "Pistol Ammunition (Large, .40-.50 caliber)",
    book: "Deadlands",
    weight: 0.1,
    costCents: 6,
  },
  {
    id: "pipe",
    name: "Pipe",
    book: "Deadlands",
    weight: 0.75,
    costCents: 200,
  },
  {
    id: "pick",
    name: "Pick",
    book: "Deadlands",
    weight: 12,
    costCents: 200,
  },
  {
    id: "percussion-caps",
    name: "Percussion caps",
    book: "Deadlands",
    weight: 0.17,
    costCents: 1,
  },
  {
    id: "owl-eye-goggles",
    name: "Owl-eye goggles",
    book: "Deadlands",
    weight: 1,
    costCents: 60000,
  },
  {
    id: "noiseless-shoes",
    name: "Noiseless Shoes",
    book: "Deadlands",
    weight: 0,
    costCents: 50000,
  },
  {
    id: "mule",
    name: "Mule",
    book: "Deadlands",
    weight: 0,
    costCents: 5000,
  },
  {
    id: "mess-kit",
    name: "Mess kit",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "mechanical-mule",
    name: "Mechanical mule",
    book: "Deadlands",
    weight: 800,
    costCents: 150000,
  },
  {
    id: "matches-box-100",
    name: "Matches (box 100)",
    book: "Deadlands",
    weight: 0.25,
    costCents: 50,
  },
  {
    id: "longjohns",
    name: "Longjohns",
    book: "Deadlands",
    weight: 2,
    costCents: 200,
  },
  {
    id: "lockpicks",
    name: "Lockpicks",
    book: "Deadlands",
    weight: 1,
    costCents: 500,
  },
  {
    id: "liquid-courage",
    name: "Liquid courage",
    book: "Deadlands",
    weight: 0,
    costCents: 3000,
  },
  {
    id: "lantern-oil-per-gallon",
    name: "Lantern oil (per gallon)",
    book: "Deadlands",
    weight: 6,
    costCents: 10,
  },
  {
    id: "lantern",
    name: "Lantern",
    book: "Deadlands",
    weight: 4,
    costCents: 250,
  },
  {
    id: "iron-skillet",
    name: "Iron Skillet",
    book: "Deadlands",
    weight: 5,
    costCents: 50,
  },
  {
    id: "horse",
    name: "Horse",
    book: "Deadlands",
    weight: 0,
    costCents: 15000,
  },
  {
    id: "holster",
    name: "Holster",
    book: "Deadlands",
    weight: 1,
    costCents: 300,
  },
  {
    id: "healing-unguent",
    name: "Healing unguent",
    book: "Deadlands",
    weight: 0,
    costCents: 8000,
  },
  {
    id: "hatchet",
    name: "Hatchet",
    book: "Deadlands",
    weight: 2.5,
    costCents: 100,
  },
  {
    id: "hat-periscope",
    name: "Hat Periscope",
    book: "Deadlands",
    weight: 12,
    costCents: 20000,
  },
  {
    id: "harmonica",
    name: "Harmonica",
    book: "Deadlands",
    weight: 0,
    costCents: 50,
  },
  {
    id: "handcuffs",
    name: "Handcuffs",
    book: "Deadlands",
    weight: 3,
    costCents: 350,
  },
  {
    id: "hammer",
    name: "Hammer",
    book: "Deadlands",
    weight: 2,
    costCents: 50,
  },
  {
    id: "gun-belt",
    name: "Gun belt",
    book: "Deadlands",
    weight: 1,
    costCents: 200,
  },
  {
    id: "guitar",
    name: "Guitar",
    book: "Deadlands",
    weight: 6,
    costCents: 800,
  },
  {
    id: "greased-lightning-pill",
    name: "Greased lightning pill",
    book: "Deadlands",
    weight: 0,
    costCents: 7500,
  },
  {
    id: "gold-ore",
    name: "Gold ore",
    book: "Deadlands",
    weight: 1,
    costCents: 32000,
  },
  {
    id: "ghost-rock-ore",
    name: "Ghost rock ore",
    book: "Deadlands",
    weight: 1,
    costCents: 10000,
  },
  {
    id: "gatling-shotgun-ammo-drum",
    name: "Gatling Shotgun Ammo Drum",
    book: "Deadlands",
    weight: 3.5,
    costCents: 500,
  },
  {
    id: "gatling-rifle-ammo-drum",
    name: "Gatling Rifle Ammo Drum",
    book: "Deadlands",
    weight: 7,
    costCents: 500,
  },
  {
    id: "gatling-pistol-ammo-drum",
    name: "Gatling Pistol Ammo Drum",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "gatling-carbine-ammo-drum",
    name: "Gatling Carbine Ammo Drum",
    book: "Deadlands",
    weight: 7,
    costCents: 500,
  },
  {
    id: "fuse-per-foot",
    name: "Fuse (per foot)",
    book: "Deadlands",
    weight: 0.1,
    costCents: 5,
  },
  {
    id: "file",
    name: "File",
    book: "Deadlands",
    weight: 1,
    costCents: 25,
  },
  {
    id: "fedora",
    name: "Fedora",
    book: "Deadlands",
    weight: 0,
    costCents: 300,
  },
  {
    id: "epitaph-camera",
    name: "Epitaph camera",
    book: "Deadlands",
    weight: 7,
    costCents: 160000,
  },
  {
    id: "electrostatic-belt",
    name: "Electrostatic belt",
    book: "Deadlands",
    weight: 7,
    costCents: 150000,
  },
  {
    id: "dynamite-plinger-3",
    name: "Dynamite Plinger (3)",
    book: "Deadlands",
    weight: 0,
    costCents: 2000,
  },
  {
    id: "duster",
    name: "Duster",
    book: "Deadlands",
    weight: 4,
    costCents: 1000,
  },
  {
    id: "drill",
    name: "Drill",
    book: "Deadlands",
    weight: 2,
    costCents: 200,
  },
  {
    id: "doctor-s-bag",
    name: "Doctor's Bag",
    book: "Deadlands",
    weight: 6,
    costCents: 1000,
  },
  {
    id: "diving-suit",
    name: "Diving Suit",
    book: "Deadlands",
    weight: 45,
    costCents: 200000,
  },
  {
    id: "disguise-kit",
    name: "Disguise kit",
    book: "Deadlands",
    weight: 8,
    costCents: 1000,
  },
  {
    id: "detonator-plunger",
    name: "Detonator, plunger",
    book: "Deadlands",
    weight: 10,
    costCents: 1000,
  },
  {
    id: "detonation-wire-per-50",
    name: "Detonation wire (per 50\u2019)",
    book: "Deadlands",
    weight: 1,
    costCents: 250,
  },
  {
    id: "derby",
    name: "Derby",
    book: "Deadlands",
    weight: 0,
    costCents: 150,
  },
  {
    id: "dehydrated-air-tablet",
    name: "Dehydrated air tablet",
    book: "Deadlands",
    weight: 0,
    costCents: 3000,
  },
  {
    id: "coffee-per-lb",
    name: "Coffee (per lb)",
    book: "Deadlands",
    weight: 1,
    costCents: 25,
  },
  {
    id: "cigar",
    name: "Cigar",
    book: "Deadlands",
    weight: 0,
    costCents: 5,
  },
  {
    id: "canteen",
    name: "Canteen",
    book: "Deadlands",
    weight: 5,
    costCents: 100,
  },
  {
    id: "camera",
    name: "Camera",
    book: "Deadlands",
    weight: 5,
    costCents: 300,
  },
  {
    id: "boots",
    name: "Boots",
    book: "Deadlands",
    weight: 4,
    costCents: 800,
  },
  {
    id: "bonnet",
    name: "Bonnet",
    book: "Deadlands",
    weight: 0,
    costCents: 200,
  },
  {
    id: "blasting-cap",
    name: "Blasting Cap",
    book: "Deadlands",
    weight: 0,
    costCents: 100,
  },
  {
    id: "bedroll",
    name: "Bedroll",
    book: "Deadlands",
    weight: 10,
    costCents: 400,
  },
  {
    id: "barbed-wire-per-yard",
    name: "Barbed wire (per yard)",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "bacon-per-lb",
    name: "Bacon (per lb)",
    book: "Deadlands",
    weight: 1,
    costCents: 15,
  },
  {
    id: "backpack",
    name: "Backpack",
    book: "Deadlands",
    weight: 3,
    costCents: 200,
  },
  {
    id: "ax-wood",
    name: "Ax, wood",
    book: "Deadlands",
    weight: 5,
    costCents: 200,
  },
  {
    id: "arrow",
    name: "Arrow",
    book: "Deadlands",
    weight: 0.2,
    costCents: 10,
  },
  {
    id: "adrenal-booster",
    name: "Adrenal booster",
    book: "Deadlands",
    weight: 0,
    costCents: 20000,
  },
];
const ARMOR_LOCATIONS = [
  { id: "head", label: "Head" },
  { id: "face", label: "Face" },
  { id: "torso", label: "Torso" },
  { id: "arms", label: "Arms" },
  { id: "legs", label: "Legs" },
  { id: "shield", label: "Shield / carried" },
];
const ARMOR_CATALOG = [
  {
    id: "native-shield-small",
    name: "Native Shield (Small)",
    book: "Deadlands",
    armor: 1,
    weight: 3,
    minStr: "d4",
    costCents: 200,
    location: "shield",
  },
  {
    id: "native-shield-medium",
    name: "Native Shield (Medium)",
    book: "Deadlands",
    armor: 2,
    weight: 5,
    minStr: "d4",
    costCents: 300,
    location: "shield",
  },
  {
    id: "native-armor",
    name: "Native Armor",
    book: "Deadlands",
    armor: 1,
    weight: 3,
    minStr: "d4",
    costCents: 200,
    location: "torso",
  },
  {
    id: "inventors-apron",
    name: "Inventor’s apron",
    book: "Deadlands",
    armor: 1,
    weight: 4,
    minStr: "d4",
    costCents: 4000,
    location: "torso",
  },
  {
    id: "chaps",
    name: "Chaps",
    book: "Deadlands",
    armor: 1,
    weight: 6,
    minStr: "d4",
    costCents: 400,
    location: "legs",
  },
  {
    id: "armored-vest-corset-light",
    name: "Armored vest/corset (light)",
    book: "Deadlands",
    armor: 1,
    weight: 5,
    minStr: "d4",
    costCents: 10000,
    location: "torso",
  },
  {
    id: "armored-vest-corset-heavy",
    name: "Armored vest/corset (heavy)",
    book: "Deadlands",
    armor: 2,
    weight: 20,
    minStr: "d6",
    costCents: 50000,
    location: "torso",
  },
  {
    id: "armored-hat-light",
    name: "Armored hat (light)",
    book: "Deadlands",
    armor: 1,
    weight: 2,
    minStr: "d4",
    costCents: 4000,
    location: "head",
  },
  {
    id: "armored-hat-heavy",
    name: "Armored hat (heavy)",
    book: "Deadlands",
    armor: 2,
    weight: 4,
    minStr: "d4",
    costCents: 8000,
    location: "head",
  },
  {
    id: "armored-duster-light",
    name: "Armored duster (light)",
    book: "Deadlands",
    armor: 1,
    weight: 10,
    minStr: "d6",
    costCents: 20000,
    location: "torso",
  },
  {
    id: "armored-duster-heavy",
    name: "Armored duster (heavy)",
    book: "Deadlands",
    armor: 2,
    weight: 20,
    minStr: "d8",
    costCents: 40000,
    location: "torso",
  },
];
const WEAPON_CATALOG = [
  {
    id: "steam-gatling",
    name: "Steam Gatling",
    book: "Deadlands",
    weight: 50,
    minStr: "d8",
    costCents: 300000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "gatling-gun-45",
    name: "Gatling Gun (.45)",
    book: "Deadlands",
    weight: 40,
    minStr: "d6",
    costCents: 150000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "gatling-rifle-ammo-drum",
    notes: "",
  },
  {
    id: "gatling-rifle-45",
    name: "Gatling Rifle (.45)",
    book: "Deadlands",
    weight: 17,
    minStr: "d8",
    costCents: 100000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "gatling-rifle-ammo-drum",
    notes: "",
  },
  {
    id: "gatling-shotgun",
    name: "Gatling Shotgun",
    book: "Deadlands",
    weight: 15,
    minStr: "d8",
    costCents: 100000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "gatling-shotgun-ammo-drum",
    notes: "",
  },
  {
    id: "steam-saw",
    name: "Steam Saw",
    book: "Deadlands",
    weight: 20,
    minStr: "d8",
    costCents: 80000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "gatling-carbine-45",
    name: "Gatling Carbine (.45)",
    book: "Deadlands",
    weight: 12,
    minStr: "d6",
    costCents: 75000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "gatling-carbine-ammo-drum",
    notes: "",
  },
  {
    id: "flamethrower",
    name: "Flamethrower",
    book: "Deadlands",
    weight: 15,
    minStr: "d6",
    costCents: 70000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "colt-buntline-special-45",
    name: "Colt Buntline Special (.45)",
    book: "Deadlands",
    weight: 3,
    minStr: "d6",
    costCents: 50000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "gatling-pistol-36",
    name: "Gatling Pistol (.36)",
    book: "Deadlands",
    weight: 5,
    minStr: "d4",
    costCents: 40000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "gatling-pistol-ammo-drum",
    notes: "",
  },
  {
    id: "ghost-steel-lance-plains-indian",
    name: "Ghost Steel Lance (Plains Indian)",
    book: "Deadlands",
    weight: 4,
    minStr: "d6",
    costCents: 10000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "ghost-steel-saber",
    name: "Ghost Steel Saber",
    book: "Deadlands",
    weight: 4,
    minStr: "d6",
    costCents: 7500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "sharp-s-big-50-50",
    name: "Sharp’s Big 50 (.50)",
    book: "Deadlands",
    weight: 11,
    minStr: "d8",
    costCents: 5000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifle-ammunition-large-50-caliber",
    notes: "",
  },
  {
    id: "colt-revolving-shotgun",
    name: "Colt Revolving Shotgun",
    book: "Deadlands",
    weight: 10,
    minStr: "d6",
    costCents: 4500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
  {
    id: "ghost-steel-club-war-bladed",
    name: "Ghost Steel Club, War (Bladed)",
    book: "Deadlands",
    weight: 6,
    minStr: "d8",
    costCents: 4000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "winchester-76-45",
    name: "Winchester ‘76 (.45)",
    book: "Deadlands",
    weight: 7,
    minStr: "d4",
    costCents: 4000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifleSmall",
    notes: "",
  },
  {
    id: "sawed-off-double-barrel-shotgun",
    name: "Sawed-Off Double-Barrel Shotgun",
    book: "Deadlands",
    weight: 6,
    minStr: "d4",
    costCents: 3600,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
  {
    id: "double-barrel-shotgun",
    name: "Double-Barrel Shotgun",
    book: "Deadlands",
    weight: 11,
    minStr: "d4",
    costCents: 3500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
  {
    id: "lemat-carbine-42",
    name: "LeMat Carbine (.42)",
    book: "Deadlands",
    weight: 9,
    minStr: "d6",
    costCents: 3500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifleSmall",
    notes: "",
  },
  {
    id: "scattergun",
    name: "Scattergun",
    book: "Deadlands",
    weight: 5,
    minStr: "d4",
    costCents: 3500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
  {
    id: "winchester-lever-action-shotgun",
    name: "Winchester Lever-Action Shotgun",
    book: "Deadlands",
    weight: 8,
    minStr: "d6",
    costCents: 3500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
  {
    id: "bullard-express-50",
    name: "Bullard Express (.50)",
    book: "Deadlands",
    weight: 11,
    minStr: "d8",
    costCents: 3000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifle-ammunition-large-50-caliber",
    notes: "",
  },
  {
    id: "evans-old-model-sporter-44",
    name: "Evans Old Model Sporter (.44)",
    book: "Deadlands",
    weight: 12,
    minStr: "d6",
    costCents: 3000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "colt-paterson-model-36-69",
    name: "Colt-Paterson Model ’36 (.69)",
    book: "Deadlands",
    weight: 12,
    minStr: "d8",
    costCents: 2500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "enfield-musket-58",
    name: "Enfield Musket (.58)",
    book: "Deadlands",
    weight: 9,
    minStr: "d6",
    costCents: 2500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifle-ammunition-large-50-caliber",
    notes: "",
  },
  {
    id: "ghost-steel-bayonet",
    name: "Ghost Steel Bayonet",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 2500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "ghost-steel-bayonet-on-rifle",
    name: "Ghost Steel Bayonet (on rifle)",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 2500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifleSmall",
    notes: "",
  },
  {
    id: "lemat-revolver-40",
    name: "Lemat Revolver (.40)",
    book: "Deadlands",
    weight: 4,
    minStr: "d6",
    costCents: 2500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "sawed-off-winchester-44-40",
    name: "Sawed-off Winchester (.44-40)",
    book: "Deadlands",
    weight: 4,
    minStr: "d4",
    costCents: 2500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifleSmall",
    notes: "",
  },
  {
    id: "single-barrel-shotgun",
    name: "Single Barrel Shotgun",
    book: "Deadlands",
    weight: 6,
    minStr: "d4",
    costCents: 2500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
  {
    id: "winchester-73-44-40",
    name: "Winchester ‘73 (.44–40)",
    book: "Deadlands",
    weight: 10,
    minStr: "d6",
    costCents: 2500,
    damage: "2d8-1",
    range: "24/48/96",
    ap: 2,
    rof: "1",
    shotsMax: 15,
    ammoType: "rifleSmall",
    notes: "",
  },
  {
    id: "ballard-72-56",
    name: "Ballard ’72 (.56)",
    book: "Deadlands",
    weight: 11,
    minStr: "d6",
    costCents: 2400,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifle-ammunition-large-50-caliber",
    notes: "",
  },
  {
    id: "dynamite-15-sticks-in-bag",
    name: "Dynamite, 15 Sticks in bag",
    book: "Deadlands",
    weight: 4,
    minStr: "d8",
    costCents: 2400,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "ghost-steel-knife-bowie",
    name: "Ghost Steel Knife, Bowie",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 2000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "lance-plains-indian",
    name: "Lance (Plains Indian)",
    book: "Deadlands",
    weight: 4,
    minStr: "d6",
    costCents: 2000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "sharps-55-57",
    name: "Sharps ’55 (.57)",
    book: "Deadlands",
    weight: 8,
    minStr: "d6",
    costCents: 1800,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifle-ammunition-large-50-caliber",
    notes: "",
  },
  {
    id: "colt-frontier-44-40",
    name: "Colt Frontier (.44-40)",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 1500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "colt-peacemaker-45",
    name: "Colt Peacemaker (.45)",
    book: "Deadlands",
    weight: 4,
    minStr: "d4",
    costCents: 1500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "ghost-steel-spear",
    name: "Ghost Steel Spear",
    book: "Deadlands",
    weight: 5,
    minStr: "d6",
    costCents: 1500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "ghost-steel-tomahawk",
    name: "Ghost Steel Tomahawk",
    book: "Deadlands",
    weight: 3,
    minStr: "d6",
    costCents: 1500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "saber",
    name: "Saber",
    book: "Deadlands",
    weight: 4,
    minStr: "d6",
    costCents: 1500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "spencer-56",
    name: "Spencer (.56)",
    book: "Deadlands",
    weight: 8,
    minStr: "d4",
    costCents: 1500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifle-ammunition-large-50-caliber",
    notes: "",
  },
  {
    id: "colt-thunderer-41",
    name: "Colt Thunderer (.41)",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 1400,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "colt-lightning-38",
    name: "Colt Lightning (.38)",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 1300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistol-ammunition-small-22-38-caliber",
    notes: "",
  },
  {
    id: "colt-army-44",
    name: "Colt Army (.44)",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 1200,
    damage: "2d6+1",
    range: "12/24/48",
    ap: 1,
    rof: "1",
    shotsMax: 6,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "dynamite-7-sticks",
    name: "Dynamite, 7 Sticks",
    book: "Deadlands",
    weight: 2,
    minStr: "d6",
    costCents: 1200,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "colt-dragoon-44",
    name: "Colt Dragoon (.44)",
    book: "Deadlands",
    weight: 4,
    minStr: "d4",
    costCents: 1100,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "colt-navy-36",
    name: "Colt Navy (.36)",
    book: "Deadlands",
    weight: 3,
    minStr: "d4",
    costCents: 1000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistol-ammunition-small-22-38-caliber",
    notes: "",
  },
  {
    id: "ghost-steel-knife",
    name: "Ghost Steel Knife",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 1000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "rapier",
    name: "Rapier",
    book: "Deadlands",
    weight: 3,
    minStr: "d4",
    costCents: 1000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "whip",
    name: "Whip",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 1000,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "starr-revolver-44",
    name: "Starr Revolver (.44)",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 900,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "club-war-bladed",
    name: "Club, War (Bladed)",
    book: "Deadlands",
    weight: 6,
    minStr: "d8",
    costCents: 800,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "colt-rainmaker-32",
    name: "Colt Rainmaker (.32)",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 800,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistol-ammunition-small-22-38-caliber",
    notes: "",
  },
  {
    id: "springfield-rifled-musket-58",
    name: "Springfield Rifled Musket (.58)",
    book: "Deadlands",
    weight: 11,
    minStr: "d6",
    costCents: 800,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifle-ammunition-large-50-caliber",
    notes: "",
  },
  {
    id: "dynamite-3-sticks",
    name: "Dynamite, 3 Sticks",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 600,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "rupertus-pepperbox-22",
    name: "Rupertus Pepperbox (.22)",
    book: "Deadlands",
    weight: 1,
    minStr: "d6",
    costCents: 600,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistol-ammunition-small-22-38-caliber",
    notes: "",
  },
  {
    id: "wesson-dagger-pistol-41",
    name: "Wesson Dagger-Pistol (.41)",
    book: "Deadlands",
    weight: 1,
    minStr: "d6",
    costCents: 600,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "bayonet",
    name: "Bayonet",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "bayonet-on-rifle",
    name: "Bayonet (on rifle)",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "rifleSmall",
    notes: "",
  },
  {
    id: "derringer-41",
    name: "Derringer (.41)",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistolLarge",
    notes: "",
  },
  {
    id: "english-1840-model-36",
    name: "English 1840 Model (.36)",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "pistol-ammunition-small-22-38-caliber",
    notes: "",
  },
  {
    id: "ghost-steel-brass-knuckles",
    name: "Ghost Steel Brass Knuckles",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 500,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "knife-bowie",
    name: "Knife, Bowie",
    book: "Deadlands",
    weight: 2,
    minStr: "d4",
    costCents: 400,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "lariat",
    name: "Lariat",
    book: "Deadlands",
    weight: 3,
    minStr: "d4",
    costCents: 400,
    damage: "Str",
    range: "Melee",
    ap: 0,
    rof: "-",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "bola",
    name: "Bola",
    book: "Deadlands",
    weight: 0.5,
    minStr: "d4",
    costCents: 300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "bow",
    name: "Bow",
    book: "Deadlands",
    weight: 2,
    minStr: "d6",
    costCents: 300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "arrow",
    notes: "",
  },
  {
    id: "club-war",
    name: "Club, War",
    book: "Deadlands",
    weight: 3,
    minStr: "d6",
    costCents: 300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "dynamite-1-stick",
    name: "Dynamite, 1 Stick",
    book: "Deadlands",
    weight: 0.5,
    minStr: "d4",
    costCents: 300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "nitro-pint",
    name: "Nitro (pint)",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "spear",
    name: "Spear",
    book: "Deadlands",
    weight: 5,
    minStr: "d6",
    costCents: 300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "tomahawk",
    name: "Tomahawk",
    book: "Deadlands",
    weight: 3,
    minStr: "d6",
    costCents: 300,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "knife",
    name: "Knife",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 200,
    damage: "Str+d4",
    range: "Melee",
    ap: 0,
    rof: "-",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "brass-knuckles",
    name: "Brass Knuckles",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 100,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "club",
    name: "Club",
    book: "Deadlands",
    weight: 1,
    minStr: "d4",
    costCents: 100,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "",
    notes: "",
  },
  {
    id: "lemat-undercarriage-shotgun-16-ga",
    name: "LeMat undercarriage Shotgun (16-ga)",
    book: "Deadlands",
    weight: 0,
    minStr: "d6",
    costCents: 0,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
  {
    id: "undermount-shotgun-for-pistol-16-ga",
    name: "Undermount Shotgun for Pistol (16-ga)",
    book: "Deadlands",
    weight: 0,
    minStr: "d6",
    costCents: 0,
    damage: "",
    range: "",
    ap: "",
    rof: "",
    shotsMax: null,
    ammoType: "shotgun-shells",
    notes: "",
  },
];
const VEHICLE_CATALOG = [
  {
    id: "whirligig-personal",
    name: "Whirligig (Personal)",
    book: "Deadlands",
    costCents: 100000,
  },
  { id: "wagon", name: "Wagon", book: "Deadlands", costCents: 20000 },
  {
    id: "velocipede",
    name: "Velocipede",
    book: "Deadlands",
    costCents: 100000,
  },
  { id: "train-car", name: "Train Car", book: "Deadlands", costCents: 800000 },
  {
    id: "super-gyro",
    name: "Super Gyro",
    book: "Deadlands",
    costCents: 400000,
  },
  {
    id: "submersible-boat",
    name: "Submersible boat",
    book: "Deadlands",
    costCents: 2000000,
  },
  {
    id: "steam-wagon",
    name: "Steam Wagon",
    book: "Deadlands",
    costCents: 150000,
  },
  { id: "steam-cart", name: "Steam Cart", book: "Deadlands", costCents: 80000 },
  { id: "stagecoach", name: "Stagecoach", book: "Deadlands", costCents: 30000 },
  {
    id: "rocket-pack",
    name: "Rocket Pack",
    book: "Deadlands",
    costCents: 210000,
  },
  {
    id: "rail-runner",
    name: "Rail Runner",
    book: "Deadlands",
    costCents: 250000,
  },
  {
    id: "powered-ornithopter",
    name: "Powered Ornithopter",
    book: "Deadlands",
    costCents: 300000,
  },
  {
    id: "paddlewheeler-large",
    name: "Paddlewheeler, Large",
    book: "Deadlands",
    costCents: 5000000,
  },
  {
    id: "paddlewheel-small",
    name: "Paddlewheel, Small",
    book: "Deadlands",
    costCents: 2000000,
  },
  {
    id: "maze-runner",
    name: "Maze Runner",
    book: "Deadlands",
    costCents: 1500000,
  },
  {
    id: "locomotive",
    name: "Locomotive",
    book: "Deadlands",
    costCents: 1500000,
  },
  { id: "carriage", name: "Carriage", book: "Deadlands", costCents: 20000 },
  {
    id: "buckboard-buggy",
    name: "Buckboard/buggy",
    book: "Deadlands",
    costCents: 7500,
  },
  { id: "bateaux", name: "Bateaux", book: "Deadlands", costCents: 5000 },
  { id: "auto-gyro", name: "Auto-Gyro", book: "Deadlands", costCents: 150000 },
  {
    id: "air-carriage",
    name: "Air Carriage",
    book: "Deadlands",
    costCents: 500000,
  },
];
